### ISSUE TITLE
Add icons (Battery status, clock, etc...)

### ISSUE THREAD

**Issue by matwlodek** [RocketRobz/TWiLightMenu#102]
Hi, 

I have DSi EU 1.4.5, running HiyaCFW and DSiMenuPlusPlus set as default menu. This several things are missing for me:
1) Battery status
2) Clock
3) Volume status
4) Touch menu
Is there any possibility, that in future DSiMenuPlusPlus on DSi will have those? 

Something like original one would be superb:
![image](https://user-images.githubusercontent.com/24829691/42632548-d45fa326-85dd-11e8-8766-390bc481a9dc.png)

Everything works like a charm, thanks for your hard work at this project!

**Comment by LuisSant** [comment]
Yeah, That Would Be Really Nice

**Comment by NightYoshi370** [comment]
@Robz8 shouldn't this be closed?

**Comment by Robz8** [comment]
@NightYoshi370 I'm considering adding 1-3 in the future, so nah.

**Comment by NightYoshi370** [comment]
I feel like this has already been implemented for some reason

**Comment by FlameKat53** [comment]
Now just the clock I guess
