### ISSUE TITLE
Issues finding BMP converters and a link for those looking for one

### ISSUE THREAD

**Issue by YYoshi241** [RocketRobz/TWiLightMenu#136]
Request: Link a BMP converter with the release.

Why? It is a pain to find an image converter to convert to ARGB 1555 BMP.

Most Image Editors only support 24bit or (if your lucky) 16bit RGB 565.

I'm leaving a link to the only converter website I could find to convert to this format. Consider putting a link to this with the releases.

https://online-converting.com/image/convert2bmp/

**Comment by MarioMasta64** [comment]
for windows: https://github.com/MrJPGames/DSiMenu---BoxArt-Downloader & https://github.com/MarioMasta64/dsimenu-plus-plus-boxart-downloader
for linux (and also windows): https://github.com/FM1337/box-art-downloader
gametdb now has .bmp images on their site no need for conversion

**Comment by piratesephiroth** [comment]
I just disable that cover display. It's a pretty useless feature.

**Comment by ApfelTV** [comment]
@MarioMasta64 you know that you can use C# apps on linux as well?

**Comment by MarioMasta64** [comment]
okay?

**Comment by NightYoshi370** [comment]
I guess this could be added to a wiki if there ever is one. I could also add it to #important on the discord

**Comment by NightYoshi370** [comment]
I added this to #important on the discord server. Closing
