### ISSUE TITLE
Add update instructions to wiki?

### ISSUE THREAD

**Issue by cjrobe** [RocketRobz/TWiLightMenu#142]
First of all, thanks for the hard work. Just updated my DSi to the latest 5.4.0, it was very smooth. The update directions are in the 5.0.0 update though and not in the wiki. It took me a little bit of time to find. 

https://github.com/Robz8/DSiMenuPlusPlus/releases/tag/v5.0.0

**Comment by NightYoshi370** [comment]
So pretty much #important on the discord, right?

**Comment by Epicpkmn11** [comment]
The update instructions are [on the wiki](https://github.com/RocketRobz/TWiLightMenu/wiki/How-to-update-TWiLight-Menu) now, so this should probably be closed
