### ISSUE TITLE
Cannot launch a game on M3DS Real

### ISSUE THREAD

**Issue by AngryKiller** [RocketRobz/TWiLightMenu#157]
**Console:** DS Lite
**TWiLightMenu++ version:** 5.4.1

**Steps to reproduce**

1. Boot your flashcart
2. Execute boot_fc.nds
3. Try to launch a game

**Expected Behavior:** When I press A to launch a game, it launches and I can play
**Actual Behavior:** When I press A to launch a game, I get "Start failed. Error 1"

**Comment by Robz8** [comment]
Did you set the flashcard in the settings screen of DSiMenu++?

**Comment by AngryKiller** [comment]
Yes I did

**Comment by AngryKiller** [comment]
I did, and I copied the content into the root of the microSD card

**Comment by AngryKiller** [comment]
I just noticed something interesting: the _nds folder appears in YSMenu, but when I go to the root of the SD card on DSiMenu++, it's not there

**Comment by FlameKat53** [comment]
It is suppose to be hidden in TWLMenu++

**Comment by NightYoshi370** [comment]
Does the M3DS support autobooting?

**Comment by NightYoshi370** [comment]
Well, from what I can tell, the M3DS Real does not support autobooting.
Therefore, you cannot launch a DS ROM from TWiLightMenu++ using your M3DS Real.

If you'd still like to use TWiLightMenu++ with your M3DS Real, perhaps look into nds-bootstrap for flashcards?
