### ISSUE TITLE
DSiMenu++ takes too long to launch

### ISSUE THREAD

**Issue by Z4CH4R13** [RocketRobz/TWiLightMenu#178]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [X ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [v1.1.0]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [v6.0.0]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

DsiMenu++ Launches in less time after Start Dsimenu++ is pressed.
 And Romhacks which worked before launch.

### Actual behaviour

Dsimenu++ takes a minute or more to launch, and Romhacks get stuck in a white screen after loading screen no error.

### Steps to reproduce

1.Open DsiMenu++ Launcher
2.Start DsiMenu++(time until launch)
3.Start Romhack.

**Comment by dubbz82** [comment]
Which specific rom hack?  I'd guess they need more specific information to properly look into this.

**Comment by Z4CH4R13** [comment]
any, even those confirmed working on the spreadsheet.  another little detail is that the images of the games get offset so  some games upon launch will have the thumbnail of the game in front of it, until it gets to the rightmost game which will appear like a duplicate exists to it's left.

**Comment by Robz8** [comment]
I've tested Mario's Holiday, and still works for me.
Also, do clean ROMs work, or is it just ROM hacks that aren't working for you?

Also, that little detail will be fixed in the next version.

**Comment by Z4CH4R13** [comment]
clean roms work, one positive though, is that plants versus zombies menu background appears during startup instead of the texture missing until it is reloaded.

**Comment by Z4CH4R13** [comment]
to be more specific mario's holiday displays an odd bluescreen on the top screen,

**Comment by Z4CH4R13** [comment]
it's the only romhack i've tested with a different outcome

**Comment by Z4CH4R13** [comment]
sorry misclicked the wrong button.

**Comment by NightYoshi370** [comment]
Have you tried using a different frontend or no frontend?
For example, try TWLoader (if it still works) or launch nds-bootstrap directly using FBI

**Comment by NightYoshi370** [comment]
That means that this issue is hath valid.

The ROM hack not working issue is related to NDS-Bootstrap, not the frontend.
The speed, though, is an issue. What SD card class do you have?

**Comment by NightYoshi370** [comment]
Have you tried formatting the SD card and restarting from scratch?

**Comment by Z4CH4R13** [comment]
yes hasn't made any difference.
