### ISSUE TITLE
French Translation bugs (settings)

### ISSUE THREAD

**Issue by pikachuk** [RocketRobz/TWiLightMenu#195]
Hello, I wanted to post an issue because the french translation of the settings of dsimenu++ is awful,
the english v is totally fine, but the french translation is not correct at all (and incomplete since a big portion is not even translated), for instance the translation of the "off" and "on" terms are incorrect, "off" has been translated to "de" while "de" in french is the equivalent of "of" not "off" and "on" has been translated to "sur" which mostly means "on top of" not "active"
these two should be "on" = "activé"  or "on"="actif" and "off"="désactivé" or "off"="inactif"
"dernière lecture rom au démarrage" is incorrect too due to the structure of the sentence, it should be "Démarrer la dernière rom lue au démarrage"
"animer des icones dsi" should be "animer les icones dsi"
This translation makes me think that the person who made the french translation is not a native french speaker, so as a native french speaker, i easily notice these issues

**Comment by NightYoshi370** [comment]
If you can make a PR to fix these issues, that would be great.
If not, I can make it for you and fix other issues as well. I'm French Canadian, and IIRC, France French and Canadian French isn't much different

**Comment by pikachuk** [comment]
I don't think it would be a problem for me to make a pr once i figure out where the translations are located

**Comment by pikachuk** [comment]
I can't find where the translation strings are located, where are they located ?

**Comment by pikachuk** [comment]
nvm I just found it

**Comment by pikachuk** [comment]
hmm I have fixed the translation of the file and have translated every sentence not translated, but I tried to build dsimenuplusplus for my 3ds and I get a white screen at boot time, it doesn't seem to come from the modified ini file in particular

**Comment by piratesephiroth** [comment]
yeah, there's something odd about main.srldr (titleandsettings) and dsimenu.srldr (romsel_dsimenutheme).
I can't build working versions of either even if I sue Linux or older devkitpro setups.

**Comment by NightYoshi370** [comment]
Well, the french translation has gotten alot of changes since this issue has opened.
I'm going to assume this issue is fixed so I'm going to close this.
If it isn't, let me know and I'll reopen it
