### ISSUE TITLE
Black screen when loading with unlaunch

### ISSUE THREAD

**Issue by Vaporeon** [RocketRobz/TWiLightMenu#197]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [X]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [X]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release 6.1.0
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

DSiMenu++ Loads

### Actual behaviour

Black screen on boot

### Steps to reproduce

Install DSiMenu++ onto a DSi with unlaunch without CFW using BOOT.NDS  as bootcode.dsi, then start it.

**Comment by RocketRobz** [comment]
Issue seems to be fixed.
