### ISSUE TITLE
Reboot Slot-1: Error has occurred. Hold power button to turn off.

### ISSUE THREAD

**Issue by YYoshi241** [RocketRobz/TWiLightMenu#200]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [X]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS (9.1)
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X]  >= 11.4 (11.7)
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release _[2.0.2]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[6.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Launch slot-1 cart. (DS Game)
### Actual behaviour
3ds system reports error. Error stated in title
### Steps to reproduce

1.Launch slot1 cart w/ reboot
2.wait
3.error

Note: tried using direct, but that stays on white screen.

**Comment by YYoshi241** [comment]
NTR

**Comment by YYoshi241** [comment]
Tried a different NTR cart. Same issue.

(Not Related) small slot1 akmenu simbol (upper right) often doesn't work when pressed.

**Comment by YYoshi241** [comment]
Still occurs on older version (5.5.1) tested on my old 3ds. Maybe because I'm trying to load a game not a Flash cart? (Though I thought DS games worked)

**Comment by YYoshi241** [comment]
Direct does work on 5.5.1 though.

**Comment by Robz8** [comment]
The reboot method probably won't work on 3DS.

**Comment by YYoshi241** [comment]
Under direct on  5.5.1 return combo returns to 3ds home menu

**Comment by YYoshi241** [comment]
In next release: Maybe remove reboot option if system type is 3ds. (Don't know if possible.) Also in next release attempt to fix Direct. Since IT DOES WORK on older versions.

**Comment by NightYoshi370** [comment]
@YYoshi241 does this happen in the latest release?

**Comment by RocketRobz** [comment]
I'm assuming not, since in later versions, it's set to Direct on default.
