### ISSUE TITLE
Guru meditation error with akmenu theme

### ISSUE THREAD

**Issue by Nomelas** [RocketRobz/TWiLightMenu#209]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release - 2.0.2
- [ ]  Nightly _[insert here commit hash]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Release - 6.1.1
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When switching to akmenu theme, it should load as expected

### Actual behaviour

When switching to akmenu theme, it causes "guru meditation error"

### Steps to reproduce

1. set dsim++ theme to akmenu 
2. exit settings
3. must delete settings.ini or change theme back to 1-3

**Comment by Nomelas** [comment]
actually, i cant seem to figure out what is causing it, but its related to acekard theme.

**Comment by Robz8** [comment]
The error appears to be caused by having a 3DS cart in the slot.

**Comment by Nomelas** [comment]
Ah ha. Yeah, if I remove the cart it works.

**Comment by Nomelas** [comment]
im still getting the error - I don't have a 3ds cart inserted, but an r4 card (r4i-sdhc.com)

**Comment by EnekoT2001** [comment]
> im still getting the error on 6.3.0 - I don't have a 3ds cart inserted, but an r4 card (r4i-sdhc.com)

This happens to me because it tries to access the slot-1 SD on a non-compatible cart, try to go to settings and turn off this feature, tell if it works

**Comment by Nomelas** [comment]
It no longer gives me an error on the latest version

**Comment by EnekoT2001** [comment]
> It no longer gives me an error on the latest version

Oh okay, cool
