### ISSUE TITLE
Pokemon Black 2 Freeze

### ISSUE THREAD

**Issue by Eevee-Trainer** [RocketRobz/TWiLightMenu#210]
While DSImenuPlusPlus is able to boot Pokemon Black and Black 2, the game freezes under the following conditions. 
 - Switching the order of party Pokemon
 - When an option is selected on the battle screen
 - Viewing the summary of a pokemon
 - When an option on the battle screen is selected, the game will either freeze completely or display an error screen instructing me to turn off the power. 

I have tried running a few different Generation 5 roms and got similar results for each. Is there something I can do to fix this issue, is additional updating required?

**Comment by Robz8** [comment]
You also tried AP-patched ROMs?

**Comment by Robz8** [comment]
Also, disable async prefetch.

**Comment by Eevee-Trainer** [comment]
I've only used roms copied over from carts. I haven't modified any settings within the app itself.

**Comment by Robz8** [comment]
Your ROM needs to be AP-patched. Try the DS Scene ROM Tool.

**Comment by Eevee-Trainer** [comment]
Thanks! I'll give it a try.

**Comment by dubbz82** [comment]
Does this now work with the AP patch in place?

**Comment by NightYoshi370** [comment]
@dubbz82 seems like it
Also, this is an issue unrelated to TWiLightMenu++.
Closing
