### ISSUE TITLE
Black screens after launching the app on n3ds

### ISSUE THREAD

**Issue by Mac435** [RocketRobz/TWiLightMenu#229]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x ]  Release _[v 6.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[v 6.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

After the click on the "launch button" in the ctr menù the app should start

### Actual behaviour

the two screens go black and anything happen after the initial ds presentation and "touch the screen", i have to close the n3ds and wait some second to reboot the console

### Steps to reproduce

1. follow the guide installing the cias/_nds trough FBI
2. starting the launcher
3. push to start the app
4. push a button on the screen

**Comment by Mac435** [comment]
i have followed this guide too:
https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide
but nothing happened

**Comment by Gusanito** [comment]
I have the same error and I've also followed the guide :/
