### ISSUE TITLE
Please support for Retrogames (Flashcards users)

### ISSUE THREAD

**Issue by fenix00853** [RocketRobz/TWiLightMenu#233]
Please could you add support for NeoDs, ApprenticeMinusDS, jEnesisDS, NitroGrafx, PokeMini, SNEmulDS, DSx86, msxDS ? at less for Flashcards users. For 3ds users maybe you could use Retroarch.

I think this is in:
TWiLightMenu-6.3.0\romsel_dsimenutheme\arm9\source\fileBrowse.cpp
TWiLightMenu-6.3.0\romsel_dsimenutheme\arm9\source\main.cpp

Regards.

**Comment by Robz8** [comment]
The question is, do they support arguments?
For 3DS, no, Retroarch is a CTR-mode app, and TWiLight Menu++ runs in TWL mode.

**Comment by lenix9090** [comment]
If that works ... They will also serve unofficial games like, DScraft

**Comment by lenix9090** [comment]
PS: In DSi (Unlauch) It does not work either

**Comment by fenix00853** [comment]
I found that there are Ext used by Moonshell to add support:

NeoDs https://filetrip.net/nds-downloads/emulators/download-neods-for-moonshell2-f5306.html
jEnesisDS https://filetrip.net/nds-downloads/emulators/download-moonshell-2-extlink-plugin-emulators-2-0-f31356.html
SNEmulDS https://filetrip.net/nds-downloads/emulators/download-unofficial-moonshell-2-snemulds06-0-6-f8731.html
ApprenticeMinusDS I think that was develop by the same author of jEnesisDS.
Regards.

**Comment by lenix9090** [comment]
lol snes:http://www.lolsnes.com/Download-lolSnes.htm

**Comment by RocketRobz** [comment]
jEnesis and SNEmulDS have been added, and require a RAM disk.
S8DS can be added for 8-bit Sega support.
