### ISSUE TITLE
.nds DSiware save corruption on Acekard theme

### ISSUE THREAD

**Issue by Gabri-kun** [RocketRobz/TWiLightMenu#234]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[6.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Should launch .nds dsiware on Acekard theme and save the Game.

### Actual behaviour

Doesn't save the game. Game says with a note that the save data is corrupted.

(Saving works flawlessly on the standard DSi theme)

### Steps to reproduce

1. Change the Theme to Acekard in the settings
2. Launch a .nds Dsiware title and press X for 2 seconds so that unlaunch (Version 1.4 in my case) can boot the Game
3. Game will say that save data is corrupted and will restart

**Comment by Valkristh** [comment]
I have more info for this issue, when a dsiware is loaded from a acekard theme a 0 byte .prv file is created even if a .pub exist and the data is deleted or corrupted, if i change to dsi theme the save data non exist 
I like akmenu because is fast for navigate in  roms folders, but this issue is not safe for the save data of dsiware games :(

**Comment by Gabri-kun** [comment]
@Valkristh  That also happened to me. Just forgot to write that xD. But still thanks for pointing that out :)

**Comment by GorGylka** [comment]
i Have same issuses. Wokrs fine on R4 Menu, DSi and 3DS theme, But not on AceCard
