### ISSUE TITLE
Long game names go off of the screen in per-game settings

### ISSUE THREAD

**Issue by TheShinyCookie** [RocketRobz/TWiLightMenu#236]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release [6.3.0]
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Ideally, when in the per-game settings menu, game names that are too long to fit on the screen should be scrolled.

### Actual behaviour

Game names that are too long just go off of the screen, even past the box containing the settings.
https://ibb.co/dRBMe9

### Steps to reproduce

1. Have a game that has a long name. In my case, it's Pokémon Mystery Dungeon - Blue Rescue Team.
2. Open the per-game settings using Select.

**Comment by TheShinyCookie** [comment]
Kinda disappointed that this has been ignored for almost a whole month. I have another issue on nds-bootstrap and that has been ignored too... the hell is this about?

**Comment by ahezard** [comment]
You know that we do not do this for a living but only as a hobby right?

**Comment by catfatwm** [comment]
this is github, if it bothers you that much fix it and issue a pull request, these guys do it for fun, and this is the last app being updated damn near for the stagnant 3ds scene. show some appreciation, and quit being an asshat. maybe join the twl discord and help figure out whats going on...
