### ISSUE TITLE
Can't change language of Hotel Dusk

### ISSUE THREAD

**Issue by graziel666** [RocketRobz/TWiLightMenu#246]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Release _[6.4.2]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour
the games should work on spanish and other languages (used them before with older versions) for example hotel dusk,

### Actual behaviour
not matter what i do it only start on default

### Steps to reproduce

1. enter on the app options and change to system, spanish or any language, try it, change game options too and try again, no matter what it should't work

**Comment by Robz8** [comment]
The ROM itself should support the language, before you can use it.
Are you sure it's the same ROM you're using?

**Comment by Robz8** [comment]
Setting Japanese in Sonic Colors works.

**Comment by graziel666** [comment]
> 
> 
> The ROM itself should support the language, before you can use it.
> Are you sure it's the same ROM you're using?

yes, in fact i use those same ROM with older versions and they work perfectly, twloader and dsimenu++, also they work on pc changing the system language it change ingame

**Comment by Terrijoo** [comment]
Can agree that it happens with Hotel Dusk. Meteos for example changed to german, Hotel Dusk stays in english.

**Comment by Laincito** [comment]
Same for me. Hotel Dusk always is in english when system language is Spanish.

**Comment by marvel2308** [comment]
I have the same problem, I do not know how to change the language to Spanish, it always comes out in English. "Last Window" if it can be played in Spanish but "Hotel Dusk" does not.

**Comment by NightYoshi370** [comment]
I think this is a problem with nds-bootstrap and not TWiLightMenu++, as from what I see, while TWiLightMenu++ sets the language in the ini, nds-bootstrap is the one responsible for changing the language

**Comment by Srzarco** [comment]
I have tried a few games and all of them change the language but that one, I tried the rom in pc and work fine.... Any ideas?

**Comment by Emitsu55** [comment]
someone could find the solution? I still have the same problem :(

**Comment by Epicpkmn11** [comment]
As @NightYoshi370 said when closing this, this is an nds-bootstrap issue, not TWiLight Menu++, specifically this is the issue on the nds-bootstrap repo: https://github.com/ahezard/nds-bootstrap/issues/654
