### ISSUE TITLE
Update "how to install" wiki for TWiLightMenu

### ISSUE THREAD

**Issue by UnicornsOnLSD** [RocketRobz/TWiLightMenu#247]
Hey, I couldn't figure out how to make a pull request for the wiki (moved to Gitlab a while ago, had to recreate my Github account for this) so I'm making an issue.

The wiki still tells people to install DSiMenu++, I edited it a bit to fix that. Here is the markdown for it below:
1) If you are coming from TWLoader/DSiMenu++, uninstall all of the TWLoader/DSiMenu++ applications using a CIA manager (for example, FBI)
2) Delete the `_nds` folder from the root of your SD card if it exists
3) Download the latest version of TWiLightMenu from the releases page: <https://github.com/Robz8/TWiLightMenu/releases>
4) Download the latest version of the TWiLightMenu launcher: <https://github.com/Robz8/TWiLightMenu-Launcher/releases>
5) Copy the `cia` folder and the `_nds` folder as well as `boot.nds` to the root of your SD card.
6) Copy `TWiLight Menu++ Launcher.cia` to the `cia` folder on the root of your SD card
7) Install all the `.cia` files found inside the `cia` folder on the root of your SD card.
[How-to-install-TWiLightMenu---(3DS).txt](https://github.com/Robz8/TWiLightMenu/files/2438457/How-to-install-TWiLightMenu---.3DS.txt)

**Comment by RocketRobz** [comment]
DSiMenu++ is just an alt name for TWiLight Menu++, so uninstalling it isn't necessary.
