### ISSUE TITLE
L+R+Down+B not working with Luma 3DS

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [RocketRobz/TWiLightMenu#248]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS 
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  **Luma3DS _9.1 - 89cc6ed_** on _11.8.0-41E_ using **boot9strap/Sighax**
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _2.1.0_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _6.4.3_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Restart into TWiLightMenu++

>With CFW: DS ROMs (on SD)/carts
L+R+DOWN+B for 2 seconds: Return to TWiLight Menu++.

### Actual behaviour

Restarts into 3DS home menu.

### Steps to reproduce

1. Launch a game with TWiLightMenu++
2. Hold L+R+Down+B for 2 seconds
3. Enjoy your home menu!

**Comment by ankorite** [comment]
Turn on game patching in Luma settings.
