### ISSUE TITLE
Homebrew roms launch as DSiWare on akmenu theme

### ISSUE THREAD

**Issue by Epicpkmn11** [RocketRobz/TWiLightMenu#249]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[6.4.3]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Rom loads, like on DSi theme

### Actual behaviour

Prompts you to hold X and says it's loading DSiWare
*The only homebrew roms I have tested with are ones that run on DSi like GodMode9i, so maybe old ds homebrew would work properly, but new stuff isn't working right*

### Steps to reproduce

1. Set theme to akmenu
2. Open a ds homebrew rom *(GodMode9i definitely has the problem)*

**Comment by mbj222** [comment]
Gonna add that is the case for every homebrew .nds file, from homebrew apps builded with devkitPRO on my PC to the really old ones.

**Comment by Epicpkmn11** [comment]
By changing this (In akmenu's arm9's dsrom.cpp):
```
else if ((header.unitCode >= 0x02 && header.arm9romOffset == 0x4000 && header.arm7binarySize < 0x20000) || (header.arm9romOffset == 0x200 && (u32)header.arm7destination == 0x02380000))
        {
            // Homebrew with DSiWare Extended header
            _isDSiWare = ETrue;
            _isHomebrew = ETrue;
        }
```
to this:
```
else if ((header.unitCode >= 0x02 && header.arm9romOffset == 0x4000 && header.arm7binarySize < 0x20000) || (header.arm9romOffset == 0x200 && (u32)header.arm7destination == 0x02380000))
        {
            // Homebrew with DSiWare Extended header
            _isDSiWare = EFalse;
            _isHomebrew = ETrue;
        }
```
and changing homebrew roms to boot using `Default` (or `Direct Boot`)instead of `Use Bootstrap` then homebrew roms work on the akmenu theme

Real DSiWare still works after changing this
