### ISSUE TITLE
ROMs ERROR | Temporary solution

### ISSUE THREAD

**Issue by lenix9090** [RocketRobz/TWiLightMenu#252]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ *]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ *]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by lenix9090** [comment]
Hello! You know my previous ROMs ERROR good. I have a temporary solution * or if it works well until permanent. Note: both options hold the same only that they are in a different way. 1._ Update and outdated: add a configuration that returns the version that is being used to 6.0.1, why 6.0.1? because 6.0.1 was the last version used before the error. 2._ One above the other. add a folder in the folder roms that is called "6.0.1" and there is the all that brings the .zip of tiwlight menu ++ (6.0.1 DsiMenu ++) and use it as if it were a game

Problems Of One On Top Of The Other.
1._ I do not think it works in HiyaCFW
2._yo, for example I use TiwlightMenu ++ from SUDOKU and I realized that when you put it, letters appear, one of those letters can REPEAT, it could be confused with 2 and error or even something bigger, the console is damaged

Thanks And Help n_n!
PD: Google Translate

**Comment by lenix9090** [comment]
ROMS ERROR here: https://github.com/RocketRobz/TWiLightMenu/issues/237

**Comment by lenix9090** [comment]
Another problem: https://github.com/RocketRobz/TWiLightMenu/issues/259

**Comment by NightYoshi370** [comment]
This doesn't look to be an issue, so I'll close this I guess
