### ISSUE TITLE
Installation Problem CIAs

### ISSUE THREAD

**Issue by lebgdu18** [RocketRobz/TWiLightMenu#253]
When I try to install the 2 cias : TWiLight Menu Game booter and TWiLight Menu with FBI it won't show the application on the main manu help me please.

**Comment by piratesephiroth** [comment]
you need the launcher

https://github.com/RocketRobz/TWiLightMenu-Launcher/releases

**Comment by lebgdu18** [comment]
WOW i'm stuîd af thanks mate
