### ISSUE TITLE
Games won't boot

### ISSUE THREAD

**Issue by RyanTheInkling** [RocketRobz/TWiLightMenu#255]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.7, and 1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please enter version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v6.4.3]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

The game should launch

### Actual behaviour
The game freezes.
### Steps to reproduce

1. Turn on DSI.
2. Launch game
3. Freezes.

**Comment by RocketRobz** [comment]
What game(s) are you trying?

**Comment by RyanTheInkling** [comment]
Cooking Mama 3: Shop and Chop

**Comment by RyanTheInkling** [comment]
I just tried all of the games, none of the games load

**Comment by RocketRobz** [comment]
Try turning off sound fix.

**Comment by RyanTheInkling** [comment]
how do i do that?

**Comment by RyanTheInkling** [comment]
It's off

**Comment by RocketRobz** [comment]
What are the exact games you tried that gave you a white screen?

**Comment by RyanTheInkling** [comment]
Some of the games have a white screen, and some have a black screen.
Here's the list:

**Comment by RyanTheInkling** [comment]
I can't copy the file names

**Comment by RyanTheInkling** [comment]
I will just downgrade back to DSi Menu ++

**Comment by RocketRobz** [comment]
Just take a screenshot of the file list.
Also, you can just downgrade the nds-bootstrap version, instead of just downgrading the TWLMenu++ frontend.

**Comment by RyanTheInkling** [comment]
![capture](https://user-images.githubusercontent.com/41594800/46575790-9acaae00-c979-11e8-9ea1-c78c0ef72b13.PNG)
![capture](https://user-images.githubusercontent.com/41594800/46575793-b59d2280-c979-11e8-99eb-416e313ca157.PNG)

**Comment by RocketRobz** [comment]
Hmm, try Sega Casino.

**Comment by RyanTheInkling** [comment]
okay

**Comment by RyanTheInkling** [comment]
it works
i think i need a older version of nds bootstrap for all games
to work
