### ISSUE TITLE
Final Fantasy Crystal Chronicles - Echoes of Time EUR - Could not save data

### ISSUE THREAD

**Issue by Shikafax** [RocketRobz/TWiLightMenu#256]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Release _[2.1.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[6.4.3]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When i try to save the game, he should save.

### Actual behaviour

When i try to save the game, appears: Could not save data. Turn off the power and reinsert the DS Game Card.

### Steps to reproduce

1. Make a new game or go to option
2. If you make a new game, Try to save
3. If you go to option, try to change something

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue.
