### ISSUE TITLE
how to uninstall TWiLight Menu.cia and TWiLight Menu - Game booter.cia

### ISSUE THREAD

**Issue by tmc9031** [RocketRobz/TWiLightMenu#257]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

i see : NOTE: If you're using EmuNAND, then install them to SysNAND as well.

1. but i really hope normal launch in emuNand without install TWiLight Menu.cia and TWiLight Menu - Game booter.cia in sysNand
2. in addition, how to uninstall TWiLight Menu.cia and TWiLight Menu - Game booter.cia ???

### Actual behaviour

after touch, boot TWiLight Menu fail

**Comment by RocketRobz** [comment]
Uninstall the TWiLight Menu++ titles in purple text in FBI.

**Comment by Micaels882** [comment]
**DSi / Unlaunch V1.8 + HiyaCFW V0.19.2 / 
I want a help to remove my unlock**

**Comment by megapples** [comment]
Do I need to delete EVERY titles in purple text or just the ones with "Twilight menu" on it?

**Comment by JonArcherII** [comment]
Just the TWiLightMenu ones.

**Comment by marbug64** [comment]
Oi eu desinstalei o twilight++menu e quando ligo o apenas o led azul acende as duas telas não acendem e o led de wifi fica desligado
