### ISSUE TITLE
Red screen of the "..."

### ISSUE THREAD

**Issue by lenix9090** [RocketRobz/TWiLightMenu#260]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

Topic: 3DS

**Comment by lenix9090** [comment]
Hello (again ...) I've been playing very normal and I get to add Call Of Duty Modern warfare 3 and sega super star tennis. but both at a certain point. a screen similar to "guru meditation error" appears only with red dots and ...

P.S: Spider-Man 3 does not save
v6.4.2
Google translator

**Comment by RocketRobz** [comment]
As mentioned by the issue template, any issue involving a game is an nds-bootstrap issue.
