### ISSUE TITLE
Loading rom in akmenu's no icon view causes Guru error

### ISSUE THREAD

**Issue by Epicpkmn11** [RocketRobz/TWiLightMenu#261]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.7+v1.3.2]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v6.4.4]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Rom loads

### Actual behaviour

If you load attempt to load a rom in the akmenu theme it will cause a Guru Meditation Error if the icon for that rom hasn't been loaded. If you switch views (Select) to one with icons and back it will work, but if you change folder or even just scroll down to a rom whose icon wasn't loaded, I get this guru error...

![guru error](https://i.postimg.cc/cLNzbDGh/IMG-4464.jpg)

### Steps to reproduce

1. Set theme to akmenu
2. Press `Select` twice
3. Scroll down or switch folders to a rom whose icon hasn't been loaded
4. Open it

**Comment by NightYoshi370** [comment]
Does this happen on the latest version?

**Comment by Epicpkmn11** [comment]
Yeah, just checked on v6.6.1 and it still crashes
