### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by 1upus** [RocketRobz/TWiLightMenu#265]
Hi, I want translate Menu to Russian, how can I do it?

**Comment by NightYoshi370** [comment]
Hey @1upus. Thanks for helping us.

There are two ways you can help translate TWiLightMenu++ to Russian.
The first way is to fork this repo, make a new file with the translated strings and send in a pull request.
Another way you can help us is just send the translation here and we can make the files ourselves.

Hope to see TWiLightMenu++ in Russian
~NightYoshi370
