### ISSUE TITLE
Problem loading games when when 'autobooting'

### ISSUE THREAD

**Issue by BOBdotEXE** [RocketRobz/TWiLightMenu#268]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _1.7_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _v6.4.5_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Games should launch normally when booted via  homebrew entry point or ulaunch auto boot.

### Actual behaviour
Games boot fine when TWiLightMenu is booted manually, But if TWiLightMenu is autobooted by ulanch, all games hang on a white screen. (after loading bar goes away)

Games only boot when launched via homebrew entry point (tested on sudoku)

### Steps to reproduce

1. start up system 
2. boot any game
3.
 
This has been an ongoing issues for me, not just with the latest version,
(sadly I can't remember what version worked last)

I've tested with a fresh dump of 'Mario Kart DS'
I've tired a few versions of Ulaunch. (1.4/1.6/1.7)  all give me the same problem
(tested with/without ds game in slot)
(DSi XL 1.4U)
8GB sandisk class4 Sd card. [ Fat32, 32k]
 

I'm just wondering if there's something I can do to fix it.
Don't spend too long worrying about it, It's possible that my DSi is just weird, I've asked around of the discord, and no one else has this issue.

[NDSBTSRP.LOG](https://github.com/RocketRobz/TWiLightMenu/files/2521442/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
It is not an issue with TWiLight Menu++ or your DSi.
It's an issue with nds-bootstrap.
Each time a version of nds-bootstrap releases, there's a low chance that it'll work with Unlaunch alone.
