### ISSUE TITLE
MANY QUESTIONS!!!

### ISSUE THREAD

**Issue by lenix9090** [RocketRobz/TWiLightMenu#269]
Hello! (again...)
I have some questions today:
1._ Can you compile in some way MoonShell for TWilight Menu ++?
2._ Is TWM ++ or is it that iPod Nano does not work? (http://www.mediafire.com/file/afsksj8xlbzx83h/Ipod+Nano.nds)
------------------------------- My Menu ++ --------------- - ---------------------
3._ For @RocketRobz: you can create an application for the Twilight ++ Menu
called My Menu ++
- And what will that do?
Improved features of The MoonShell
-As..? What!?
Well as: watch videos, listen to music, draw, draw + (to animate and create custom themes for the Twilight ++ Menu) Photos (only for DSi and 3DS) Edit .txt and Make .txt, A .nds Designer As creator of Games or Build 2/3 (FPS Editor)
And if possible compatible up to R4 !!!
PS: I am aware that this is a lot, but although you can get something out !!! ;D
PS: I know that the "Design" games is very difficult but although it is something basic or separate to My Menu ++ (if it works it can be called DS Gamers Makes Engine)

Google translator

**Comment by RocketRobz** [comment]
1. It's not open-source, but if it is, can you post a link to it?
2. It's an issue on nds-bootstrap's side, not TWiLight Menu++.
3. Anything such as video/music playback from a device, or a game creator, is way beyond my coding knowledge, so probably not.
Editing/Making .txt files, should be in a future version of GodMode9i though.
Also, any homebrew that's made with DLDI support (which is already included), will work on most (if not all) flashcards, even the R4.

Also, please don't use the issue tracker for assistance or questions.
For any future assistance or questions, please go to any of these Discord servers.
https://discord.gg/XRXjzY5 <- DS(i)Brew Scene (this has an assistance text channel in spanish)
https://discord.gg/7aAYUEf <- TWL Mode Hacking!

**Comment by lenix9090** [comment]
I understand clearly!

**Comment by lenix9090** [comment]
Hi @RocketRobz ! was searching Google "MoonShell" AND I FOUND ME MOONSHELL SOURCE CODE! Here: https://gbatemp.net/download/moonshell-source-code.33483/download?version=33483

**Comment by RocketRobz** [comment]
Thanks, but I found that I already downloaded it, and would take a lot of work to get it working on latest devkitArm/libnds.

**Comment by lenix9090** [comment]
Okay!!! n_n
