### ISSUE TITLE
Can't launch retail games

### ISSUE THREAD

**Issue by TheRamsWay** [RocketRobz/TWiLightMenu#271]
I'm using v6.5.0 on an original R4 and DS Lite, but I can't manage to launch retail games, I always get "Start failed. Error 0". It's probably just me being stupid but I really don't know what to do

**Comment by RocketRobz** [comment]
This is normal. TWiLight Menu++ cannot run retail/commercial ROMs on the original R4.
Wait for a flashcard-compatible version of nds-bootstrap to be released.

**Comment by TheRamsWay** [comment]
That explains a lot...
So is there any way to launch them with YSMenu instead? I've seen some older R4 menu replacement use that (although for some games, it just loaded YSMenu instead of lauching the game with it)

**Comment by RocketRobz** [comment]
Yes. Use the default firmware to boot `YSMenu.nds`.

**Comment by TheRamsWay** [comment]
I was thinking about using TWiLight as the menu and YSMenu as the loader but I assume YSMenu as both is the best I can currently have.
Anyway, thanks a lot for helping me that quickly! I'll just wait for a compatible nds-bootstrap (or invest in a newer console...)

**Comment by TheRamsWay** [comment]
As I can see on v6.8.0 changelog, a flashcard version of nds-bootstrap is planned. Is it out yet? I tried v7.2.0, got a black top screen and white bottom screen when launching a retail game.

**Comment by TheRamsWay** [comment]
As I can see on v6.8.0 changelog, a flashcard version of nds-bootstrap is planned. Is it out yet? I tried v7.2.0, got a black top screen and white bottom screen when launching a retail game.

**Comment by Epicpkmn11** [comment]
It's here: https://github.com/ahezard/nds-bootstrap/tree/flashcart-wip if you want to build it yourself, it hasn't had a release yet.

**Comment by TheRamsWay** [comment]
I didn't even realized there was a Branch button....
Thanks a lot, I'll try that and see if it works!

**Comment by TheRamsWay** [comment]
Same problem with the flashcard version

**Comment by NightYoshi370** [comment]
So does it now work?

**Comment by NightYoshi370** [comment]
Try L + R + START + SELECT. If that doesn't work, try L + R + B + DOWN

**Comment by TheRamsWay** [comment]
It doesn't work. Maybe it's a bug with the flashcard branch that I should report on the nds-bootsrap repo?

**Comment by NightYoshi370** [comment]
Yeah, you should do that there.
I guess now that it's dealt with, I can close this. Let me know if you need this open again.
