### ISSUE TITLE
Cheat Code Menu

### ISSUE THREAD

**Issue by JeanLouisss** [RocketRobz/TWiLightMenu#272]
Does Cheats Codes menu for games will be add to TwilighMenu 1 day ? Like the old R4

**Comment by Epicpkmn11** [comment]
Once #323 gets merged the Acekard theme will have a functional cheat menu.
(The other themes will still need a menu, though)

**Comment by Epicpkmn11** [comment]
Still not a real cheat menu, but as of #330 the DSi, 3DS, and R4 themes and the Main Menu will load any enabled cheats from `sd:/_nds/TWiLightMenu/cheats/usrcheat.dat`, so now you can use the Acekard theme to enable / disable the cheats you want, then you're free to use any of the other themes or the main menu with those cheats enabled.

**Comment by Epicpkmn11** [comment]
#333 Adds a cheat menu to the R4 theme, meaning only DSi/3DS (any maybe Main Menu?) left!

It should be reasonably simple to port my R4 code to DSi (or mainmenu) since their code is very similar, but since I can't build DSi I'm not really able to do it...

**Comment by NightYoshi370** [comment]
Is this fully implemented at this point? If so, let me know so I can close this

**Comment by Epicpkmn11** [comment]
The only thing without a cheat menu is the Main Menu, but I don't think that really needs one, so yeah, I'd say it's fully implemented
(I could add it to the main menu pretty easily though if that's wanted)

**Comment by NightYoshi370** [comment]
Welp, that's a question directed to @RocketRobz, though I would personally find it cool if you did so.

**Comment by RocketRobz** [comment]
The Main Menu is fine without the cheat menu.

**Comment by MrRed21** [comment]
> 
> 
> A cheat menu will be added soon.

hello i need some help with something and ill be very gratefull if you could help me,the problem is that i want to play pokemon heartgold with cheats but when i activate the cheats the game doesnt start it only goes to a white screen but when i start the game without cheats the gam works perfectly fine, have any idea on whats wrong?
