### ISSUE TITLE
COD: Black Ops DS Zombies mode.

### ISSUE THREAD

**Issue by DreNess7755** [RocketRobz/TWiLightMenu#273]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using: Last version 2.1.0

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using: Last version 6.5.0

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

Hello, when I play balck ops ds I can't find Zombies mode so I can't play it, but when I try on Desmume it appears and I can play Zombies. any ideas ?

**Comment by RinMaru** [comment]
plz add the version your using and what hardware you on

**Comment by DreNess7755** [comment]
done

**Comment by RinMaru** [comment]
have you tried diff options like switching between TWL and NTR speed, DSi/DS mode, and turning VRAM boost on and off? cause I think zombies worked a few months ago

**Comment by DreNess7755** [comment]
ok i'll check thanks and sorry for the late :(

**Comment by RocketRobz** [comment]
Seems to be an AP issue.
