### ISSUE TITLE
Visible save files in games list when using a mac

### ISSUE THREAD

**Issue by Kibblesh** [RocketRobz/TWiLightMenu#275]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x ]  DSi
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

Tell us which CFW do you have:

DSi:

- [ x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

Tell us which versions you are using:

- [ x]  Release _[6.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour
Tell us what should happen
Load roms from mac/windows laptop and play roms on dsi as normal. When going through menu, all that appear is games and folders, no sav file is visible.

### Actual behaviour
Tell us what happens instead
I load the rom from my MAC laptop (maybe has a notable difference from PC) onto my dsi and play the game. It creates a sav file, all good. I go ahead and finish playing and finish, exiting the game. Next time when i load twilight menu, i notice the list of games got noticably longer. I sift through the list and find a visible sav file, labeled as "*title of game*" then under, "no info". It's not any other file because when i go through my sd card there is no other file than the actual game and the sav file. Normally I wouldn't be affected much, but my menu space is getting filled up and half of it is because of the no info files. I also tried to reformat the sd card on my windows laptop, and put all the files back on, but the blank files still appear in the ds. This only happens when i import games from my mac. I would delete the sav files and import the same games from windows, but i don't want to lose my progress (tru gamer).

### Steps to reproduce

1. Get games and import from mac to sd card. (sd card was previously formatted on a pc on default settings, fat 32, such and such.)
2. Once twilight menu loads, play the newly imported game from the mac.
3. After finishing, restart dsi and get into twilight menu again, at the beginning of the list there's a file with the title of the game with "no info" under it. The file picture is blank.
![img_4305](https://user-images.githubusercontent.com/42279259/48804625-04a0dc00-ecca-11e8-9deb-1aa819075fd8.JPG)

**Comment by Epicpkmn11** [comment]
It's not the save files, macOS creates index files called ._filename and those show up in TWiLight. I made this https://github.com/Epicpkmn11/Remove-._-files/releases python script to get rid of them, and there are a few apps for it too

**Comment by RocketRobz** [comment]
^Yes. It's an issue with macOS.

**Comment by dubbz82** [comment]
Would it make sense to adjust the display to simply skip anything prefixed with ._
