### ISSUE TITLE
Graphical issues Yoshi island DS

### ISSUE THREAD

**Issue by jcmejia** [RocketRobz/TWiLightMenu#276]
Ok im posting this issue cause I was trying to play yoshi island ds but apparently at the title screen the sky isn't blue its black plus the file select menu is also missed some stuff please fix.

**Comment by RocketRobz** [comment]
Weird. The compatibility list doesn't state those issues.
Is the issue random or consistent?

**Comment by jcmejia** [comment]
I tested it out just earlier yeah it currently has issues

**Comment by jcmejia** [comment]
Then I went to twloader to see if it had that same issue and no just
twilight menu has the graphical issue

**Comment by jcmejia** [comment]
That's directly from twilight menu ++ it's the latest version I know cause
I just updated it console is new 3ds running luma 3ds+b9s

**Comment by RocketRobz** [comment]
What are your settings in TWiLight Menu++ settings?
Also, TWLoader uses older nds-bootstrap versions.

**Comment by jcmejia** [comment]
The image I sent is from twilight menu ++

**Comment by jcmejia** [comment]
Oh and I have the latest nds bootstrap working on twloader seems to be
working better than the old update except for the audio issues

**Comment by jcmejia** [comment]
Yoshi's island ss still has the same issue I will upload a video to YouTube so you can check it out

**Comment by RocketRobz** [comment]
Nothing is changed in nds-bootstrap.

**Comment by jcmejia** [comment]
I will upload a video in a bit so you can check it out I will show the
settings too

**Comment by jcmejia** [comment]
I will just stick with twloader till twilight menu is more stable I will
send you that video in a bit apparently it's not just the title screen and
menu it's also affecting in game too

**Comment by jcmejia** [comment]
https://youtu.be/MpEsbX4-LQY

**Comment by RocketRobz** [comment]
Try turning off both sound fix and VRAM boost options.

**Comment by jcmejia** [comment]
Does the same thing

**Comment by RocketRobz** [comment]
Just recently tried Yoshi's Island DS. No graphical issues on my end.
The ROM I'm using is USA (Rev01/v01).

**Comment by jcmejia** [comment]
So there's multiple revisions of the rom huh wonder which one I have hold
up let me redownload it and try again

**Comment by jcmejia** [comment]
Just tried the one you tried it does the same thing I give up I'm just
gonna stick with twloader until twilight menu ++ is more stable

**Comment by RocketRobz** [comment]
Ok, so I was able to reproduce the issue.
It is caused by turning DSi mode on, which currently doesn't have any benefits, and prevents DSi-Enhanced games from starting.
