### ISSUE TITLE
White screen in Final Fantasy and GOH

### ISSUE THREAD

**Issue by Tsuyk** [RocketRobz/TWiLightMenu#277]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

This launches TWiLight Menu++ on 3DS/2DS.

- [x ]  Release _[2.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

- [x ]  Release _[6.5.1]_
- [ ]  Nightly _[insert here commit hash]_

Tell us what should happen

**I tried to run these 2 games and both don't run, it got frozen on a white screen
1- Final Fantasy: The 4 Heroes of Light DS
2- Glory Of Heracles DS**

**Comment by RocketRobz** [comment]
1. Is sound fix off?
2. Is Final Fantasy: The 4 Heroes of Light, AP-patched?

**Comment by Tsuyk** [comment]
> 
> 
>     1. Is sound fix off?
> 
>     2. Is Final Fantasy: The 4 Heroes of Light, AP-patched?

1 launcher sound working
2 I don't know if it has ap fix for ff4heroes

**Comment by RocketRobz** [comment]
I meant is the option called `Sound fix` off in the TWiLight Menu++ settings?
Also, yes, there is an AP patch for FF 4Heroes.

**Comment by Tsuyk** [comment]
It's off, is it to activate?

**Comment by Tsuyk** [comment]
I have not tested others yet, I downloaded to play these 2 games, but I will test others later. =]

**Comment by Tsuyk** [comment]
@RocketRobz 
I tested in more games, and gave the same problem
1- lunar dragon song ds
2- luminous arc 1 and 2 ds
3- Lufia curse of the sinistrals ds
4 - pokemon black 2 patched (the pokemon game run, but freezes on a black screen when you open and close the party)

maybe the problem is my 3ds or the program, I'll wait for another update =/

**Comment by RocketRobz** [comment]
Another update won't fix your issue, because it works fine for others.
Try checking your SD card for errors.

**Comment by NightYoshi370** [comment]
This appears to be an issue unrelated to TWiLightMenu++.
Closing.
