### ISSUE TITLE
Games are crashing (Twilight Menu)

### ISSUE THREAD

**Issue by BigBoss320** [RocketRobz/TWiLightMenu#278]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [. ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [. ]  Other CFW [bootstraps on 3ds 11.8.0-41E]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [. ]  Release _[2.1.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ .]  Release _[6.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### Actual behaviour

Mario & Luigi: bowser's inside story does not start.
Zelda:Phantom hourglass, crash at each transitions.

**Comment by RocketRobz** [comment]
The issue of BiS is an AP issue, and won't be fixed 'til a new nds-bootstrap version is released. If it's stuck at white screens on boot however, then make sure your ROM isn't corrupted.
The PH issue is an nds-bootstrap issue.
