### ISSUE TITLE
Possibility of supporting Zip'd ROM Files?

### ISSUE THREAD

**Issue by imPRAGMA** [RocketRobz/TWiLightMenu#280]
Is this a possibility at all? It would be really handy and save me a TON of space

**Comment by piratesephiroth** [comment]
I don't think they have enough RAM for that

**Comment by RocketRobz** [comment]
It would also take more time for the ROM to start.

**Comment by imPRAGMA** [comment]
Alright I thought id ask anyway haha

**Comment by DMSalesman** [comment]
@imPRAGMA Remember that, if on 3DS, GodMode9 can trim your .nds files.
