### ISSUE TITLE
Cant choose Russian language 

### ISSUE THREAD

**Issue by mbhz** [RocketRobz/TWiLightMenu#281]
Hello!)
Recently I wrote a translation into Russian and it was accepted (.ini file). Today I download a new release,  but I cant choose it, It's not shown in language settings. Maby I'm missing something, or it was not enough for adding new languages?

**Comment by RocketRobz** [comment]
It was not enough. The code itself needs to read the .ini file, but since there are no Russian character graphics implemented, it's can't be displayed.

**Comment by mbhz** [comment]
Ok, so... someone will do this? Or, maybe, I can help with something?..

**Comment by RocketRobz** [comment]
Someone will probably get it working.

**Comment by mbhz** [comment]
Ok, thank you)

**Comment by 1upus** [comment]
So, can i help with cyrillic font bitmaps?

**Comment by 1upus** [comment]
Looks like cyrillic fonts already presented in TWLFontTable.dat but have incorrect spaces.
Is TWLFontTable.dat reading from sd?
![twlfonttable2](https://user-images.githubusercontent.com/21283299/50491149-f610b780-0a21-11e9-94a3-18a8057cc2c5.jpg)
![twlfonttable](https://user-images.githubusercontent.com/21283299/50491150-f610b780-0a21-11e9-9b18-e4511309ce35.jpg)
Left - its modified TWLFontTable.dat with correct spacing, right - original cyrillic font.
