### ISSUE TITLE
Stuck at Loading Screen, with 6.6.1

### ISSUE THREAD

**Issue by OldGnashburg** [RocketRobz/TWiLightMenu#282]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW _[HiyaCFW v.2.9.1 and latest unlaunch]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[v.6.6.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour
It should should be able to read my file folders so I can browse DSiWare and DS Games

### Actual behaviour
When I initially launched the menu I was able to view my files. But on a second boot it's permanently stuck at now loading

### Steps to reproduce

1. Hack your DSi with this Guide [https://dsi.cfw.guide/](url)
2. Due to an oversized SD, did the workaround by replacing TWiLight Menu with my System Menu.
3. Turn on my DSi and run TWiLight Menu++, turn off and on again.

**Comment by RocketRobz** [comment]
Do this to your all of your `.launcharg` files: Remove `content/000000##.app` at the end, using a text editor.
