### ISSUE TITLE
Stuck in a black screen after game's reboot (Pokémon Platinum (U))

### ISSUE THREAD

**Issue by SegaSystem16C** [RocketRobz/TWiLightMenu#283]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x ]  Release 2.1.0
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release 6.5.0
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

After beating the Elite Four and entering the Hall of Fame, the should fully restart after the Ending animation. This is not a simple "return to the title screen" behavior, the game should fully reboot from the beginning after the "FIN" screen. Makes me think about other NDS games that require these reboots, might present a problem for other games. I know all NDS Pokémon games do this after the Champion battle. 

### Actual behaviour

After the "FIN" screen, the game gets softlocked in a black screen. I could see my 3DS was still in the TWL Mode. I tried to return to TwiLight Menu's main menu using L+R+B+Down, but it didn't worked. Using Power to force close the app works.

### Steps to reproduce

1. Defeat Cynthia at the Pokémon League;
2. Enter the Hall of Fame, let the game save and watch the Ending animation;
3. Get stuck at the black screen after the Ending sequence is over.

**Comment by RocketRobz** [comment]
Closing, as this is an nds-bootstrap issue.
