### ISSUE TITLE
AP Patch Message Thingy

### ISSUE THREAD

**Issue by Grendelia** [RocketRobz/TWiLightMenu#284]
So the AP patch message still shows up even if i have the patch... anyone knows whats up?

**Comment by RocketRobz** [comment]
That's normal. It does not check if a ROM is AP-patched or not, so the message will still be shown.

**Comment by Grendelia** [comment]
ah mk thanks fam

**Comment by WalaRocks18** [comment]
@RocketRobz , can you put an option to remove the message alert?
Nothing wrong with it, but you know... some people might not be comfortable with that. :P

**Comment by dubbz82** [comment]
I think it would be a good idea as something that can be set per-game as "do not display again for this game".  It's better to have it prompt at least once though, in case the user isn't aware that a game may be AP protected.
