### ISSUE TITLE
More subtle loading screen?

### ISSUE THREAD

**Issue by gingerbeardman** [RocketRobz/TWiLightMenu#287]
### Your console

Tell us which console do you have:

- [x]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have: 

DSi:

- [x]  Unlaunch+HiyaCFW _[1.8+1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.13.0]_

### Expected behaviour

Subtle loading screen like the one that appears as TWLM++ itself loads, with the small spinner in the lower right and message in the lower left

### Actual behaviour

HUGE loading, spinner, and progress bar

**Comment by RocketRobz** [comment]
The big loading screen comes from nds-bootstrap, so this is an nds-bootstrap issue.
