### ISSUE TITLE
Mario Kart Ds Won Load

### ISSUE THREAD

**Issue by IceNess1** [RocketRobz/TWiLightMenu#289]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by IceNess1** [comment]
When I Load Up Mario kart Ds It Load the loading screen but the game will just sit in a white screen any help

**Comment by Epicpkmn11** [comment]
Are you launching `HIYACFW` or `TWLMENUPP` in Unlaunch? you should be launching `HIYACFW`

**Comment by IceNess1** [comment]
TWLMenu

**Comment by Epicpkmn11** [comment]
You should close this and ask on one of the Discord servers linked on dsi.cfw.guide as this is not a problem with TWiLight Menu++

**Comment by IceNess1** [comment]
cant

**Comment by IceNess1** [comment]
banned from nintendo homebrew

**Comment by IceNess1** [comment]
now how could i launch TWILightmenu from hiyacfw

**Comment by Epicpkmn11** [comment]
If you set unlaunch's `OPTIONS` > `NO BUTTON` > to `HIYACFW` does it launch, or get stuck/error?

**Comment by IceNess1** [comment]
work

**Comment by IceNess1** [comment]
it works

**Comment by Epicpkmn11** [comment]
ok, do games work using that?

**Comment by IceNess1** [comment]
then what

**Comment by Epicpkmn11** [comment]
Is Mario Kart working now using Hiya?

**Comment by IceNess1** [comment]
idk

**Comment by IceNess1** [comment]
il have to try

**Comment by NightYoshi370** [comment]
@IceNess1 can you not spam the comments?
Also, this is irrelevant to TWiLightMenu++ so I'm closing this
