### ISSUE TITLE
Sega Master System Support.

### ISSUE THREAD

**Issue by ghost** [RocketRobz/TWiLightMenu#29]
Since Gameboy & NES has Support on SRLoader, so Add Master System Support & use s8ds.

**Comment by Robz8** [comment]
Does s8ds work on SD card, though?

**Comment by hexhare** [comment]
in order for it to Work, i would need to make a TWL Build of s8ds.

**Comment by Robz8** [comment]
The source code of s8ds is needed to make a TWL build, although I don't think the source code is public, so a TWL build may not happen.

**Comment by Lykie** [comment]
http://web.archive.org/web/20150509114546/http://www.ndsretro.com:80/ndsdown.html
Only the source for 0.1 is available. Based on the later updates, it doesn't seem like too much was added.
http://web.archive.org/web/20150502191815/http://www.ndsretro.com/index.html

**Comment by pyrfol** [comment]
Don't Close this until SMS Support gets Added.

**Comment by ahezard** [comment]
s8ds is based on devKitARM/libnds, it should works with the homebrew/dldi branch of nds-bootstrap . Did you tried to run s8ds via SRLoader on a dsi or TWLoader on 3ds?

**Comment by ahezard** [comment]
I got v0.1 of s8ds to works on a 3ds using https://github.com/ahezard/nds-hb-menu/releases/tag/V0.5.0-cia-ntr-beta.6 so there is definitely some hope here
The v0.7 is not working for some reason and srloader/twloader have some issues with it as well, even with the v0.1 for some reason I do not know.

**Comment by ahezard** [comment]
Even the V0.2 does not works : I cannot enter into the menu

**Comment by ahezard** [comment]
I got v0.1 of s8ds to works on a DSI as well, still thanks to  https://github.com/ahezard/nds-hb-menu/releases/tag/V0.5.0-cia-ntr-beta.6 and HiyaCFW. It works really well with Alex Kidd and Wonder Boy: The Dragon's Trap.

**Comment by NightYoshi370** [comment]
Hey, can anyone test this out using the ramdisk thingy?

**Comment by NightYoshi370** [comment]
Loading S8DS is now fully implemented in the R4 themes and the 3DS/DSi themes. However, I think they are yet to be implemented in the Acekard theme
