### ISSUE TITLE
Main Menu changed part-way to a dark theme [6.8.1 Rev 02]

### ISSUE THREAD

**Issue by starg09** [RocketRobz/TWiLightMenu#296]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.8+2.9.9.2?]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[6.8.1 Rev 02]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Having the new Main Menu match the selected theme, like it did in 6.8.0 (Dsi - Normal/White). I understand the white version may have been default for any theme though.

### Actual behaviour

Now the main menu shows in a dark theme, which I'm not that fond of. Top screen does show up in the previous light scheme (with green details, matching my native system preference... Again, not sure if that's intended or not but pointing it out just in case)

### Steps to reproduce

1. Be in 6.7.0
2. Update to 6.8.0
3. Update to 6.8.1 Rev 02, following the provided instructions in the release, this is how it looks in my console:

![](https://i.imgur.com/zO9Qrjh.jpg)

**Comment by RocketRobz** [comment]
Fixed. Please redownload the latest version.
