### ISSUE TITLE
[REQUEST ] New Pokémon Acekard Sub-Theme

### ISSUE THREAD

**Issue by XxPhoenix1996xX** [RocketRobz/TWiLightMenu#300]
Hello, I'd like to know if there's any possibility to add a new sub-theme to the Acekard theme, I'm attaching a .zip file with the skin archives used on my flashcard. [Pokemon Black 2.zip](https://github.com/RocketRobz/TWiLightMenu/files/2718551/Pokemon.Black.2.zip)

I also have a few other, just in case you want to add them: [Acekard Subthemes.zip](https://github.com/RocketRobz/TWiLightMenu/files/2718563/Acekard.Subthemes.zip)

Thanks for this amazing project!

**Comment by FlameKat53** [comment]
@NightYoshi370 add request

**Comment by FlameKat53** [comment]
Also you can add themes yourself, just replace one that is already in the folder
