### ISSUE TITLE
AP alert shows on game that doesn't have AP

### ISSUE THREAD

**Issue by DMSalesman** [RocketRobz/TWiLightMenu#305]
The title "Rune Factory 3 - A Fantasy Harvest Moon" (BRFP) doesn't appear to have AP, but the popup is shown anyway. 

No AP patches are available.

**Comment by RocketRobz** [comment]
Because the title ID starts with B, it assumes it has AP, so it shows the message.

**Comment by DMSalesman** [comment]
Noticed that from the source. You might want to whitelist it, if no issue arises.

**Comment by piratesephiroth** [comment]
the pop up states clearly that the game MAY have AP, not that it has for sure.

**Comment by DMSalesman** [comment]
Well, it's your decision, not mine. I can only test and report back.

**Comment by NightYoshi370** [comment]
@DMSalesman are you sure it does not contain Anti-Piracy?

**Comment by DMSalesman** [comment]
I couldn't find mentions of AP measures, and Romulation agrees that there aren't any.
