### ISSUE TITLE
TWiLight Menu++ problems with the new save method

### ISSUE THREAD

**Issue by nabilhoche83** [RocketRobz/TWiLightMenu#306]
### Your console

old 3ds

### CFW and configuration

Tell us which CFW do you have:
luma 9.1

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

2.1.1
### TWiLight Menu++ version
v6.8.3 (Rev 03)

### Expected behaviour
the saves should work
### Actual behaviour
some saves do not work.
problem:
Hello
I'm having problems with the new TWiLight Menu ++ saving method
on the download page it says that I have to create a saves folder in the folder where I have the games
I do that but some saves do not work (I say some since other saves work)
there will be no way to reuse the old method of saving or at least solve the problem
(if they ask for the saves that do not work now they worked in previous versions)
thank you and I hope you solve my problem
(sorry for my bad english)

**Comment by RocketRobz** [comment]
Did you move the actual .sav files to the new folder?

**Comment by nabilhoche83** [comment]
> Did you move the actual .sav files to the new folder?

yeah

**Comment by RocketRobz** [comment]
Can you explain how some saves aren't working?

**Comment by nabilhoche83** [comment]
> Can you explain how some saves aren't working?

when passing the files to the save folder
the games super mario 64 ds, animal crossing wild world, kirby squead squad, sally salon (unknown game), new zealand story revolution, tloz spirit tracks and  m&l partners in time detect the saves
but the games mario kart zero (a rom hack), pvz, yoshi island ds, pokemon mystery dungeon explorers of sky and mlbis.
games that do not detect the save simply create new data.

**Comment by RocketRobz** [comment]
Where is the new data created?

**Comment by nabilhoche83** [comment]
> Where is the new data created?

in the new save folder 
Look at this capture of mlbis I have not yet created the save data but when playing for the second time in the beginning it did not tell me anything to create data (since when playing it for the first time it appears a text of creation of data).
before that version of twilight menu ++ the save was in plack beach.
![49204536_285088992201395_5853290338474524672_n](https://user-images.githubusercontent.com/46081056/50658329-64e49800-0f6f-11e9-828f-541190acdccd.jpg)

**Comment by RocketRobz** [comment]
It read my save in the new folder just fine.
It was created outside of that folder.

Are you sure you're using Rev 03 of v6.8.3 of TWLMenu++?

**Comment by nabilhoche83** [comment]
> It read my save in the new folder just fine.
> It was created outside of that folder.
> 
> Are you sure you're using Rev 03 of v6.8.3 of TWLMenu++?

yes
![48984833_1902271486537067_7962026591121309696_n](https://user-images.githubusercontent.com/46081056/50658989-7c248500-0f71-11e9-90a8-5ef8cf76a1b5.jpg)

**Comment by RocketRobz** [comment]
Try re-updating.

**Comment by nabilhoche83** [comment]
> Try re-updating.


ok I'll do it and later I'll tell you what happens and I'll also put the rom in another folder

**Comment by nabilhoche83** [comment]
> Try re-updating.

I discovered something
some saves are saved in the folder where I have the ROMs and not in the saves folder and when I copy the old saves they did not work

**Comment by nabilhoche83** [comment]
> Try re-updating.
hello I solved the problem (partially) I copied the only saves that I have backed up and moved them to both folders (to the games and the new folder) and they worked

**Comment by RocketRobz** [comment]
Turns out this is an nds-bootstrap issue.
Closing.

**Comment by arudorusu** [comment]
how do i save files on TWilight menu++?
