### ISSUE TITLE
The ability to re-arrange the apps for the DSi Menu Theme

### ISSUE THREAD

**Issue by ChampionLeake** [RocketRobz/TWiLightMenu#307]
Something I think that would be actually nice and pretty cool.
A feature to be able to rearrange the app placements like the normal system launcher instead of apps/roms being alphabetically in order due to the name of the file.

**Comment by FlameKat53** [comment]
Just rename your ROMs to apokemon.nds bmario.nds etc.

**Comment by FlameKat53** [comment]
well, Epicpkmn11 is working on it

**Comment by Epicpkmn11** [comment]
#357 will add this feature
