### ISSUE TITLE
Soft Reset Issue

### ISSUE THREAD

**Issue by donaquill** [RocketRobz/TWiLightMenu#308]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x ]  Release _[1.1.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[6.8.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour
Soft Reset

Reset game, go back to start menu
### Actual behaviour
White screen

White screen that freezes TWiLight and makes me go back to home menu
### Steps to reproduce

1. Go to any game
2. L+R+Start+Select
3. Freeze

**Comment by RocketRobz** [comment]
What game was this tested on?

**Comment by donaquill** [comment]
Pokemon Soul Silver

**Comment by RocketRobz** [comment]
Try updating nds-bootstrap.
Soft-resetting works fine for me.
