### ISSUE TITLE
Cia TWILight Menu version for 3ds wont work 

### ISSUE THREAD

**Issue by IceNess1** [RocketRobz/TWiLightMenu#312]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [x]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by IceNess1** [comment]
when i run FBI i download twilight then when it finished i press the home menu and i dont see TWILight Menu Any help

**Comment by FlameKat53** [comment]
You must install the launcher

**Comment by FlameKat53** [comment]
github.com/RocketRobz/TWiLightMenu-Updater

**Comment by Volti-p** [comment]
Follow the Wiki. https://github.com/RocketRobz/TWiLightMenu/wiki/How-to-install-TWiLight-Menu---(3DS)
