### ISSUE TITLE
nanashi no game(english patch 1.2) goes black screen.

### ISSUE THREAD

**Issue by hmc1242** [RocketRobz/TWiLightMenu#313]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

--------------------------------------------------------

when i start the game, it shows square enix and actimagine logo. after that i get just a black screen.
the title screen doesn't show up.

I have Twilightmenu v7.0.0(include nds-bootstrap v1.14.1), twilight menu launcher v2.1.1, luma3ds v9.1. 
and my 3ds system version is 11.9.0.

---------------------------------------------------------

**Comment by NightYoshi370** [comment]
This is an nds-bootstrap issue, not one with TWiLightMenu++
