### ISSUE TITLE
GBA link with DS roms

### ISSUE THREAD

**Issue by Shinigati** [RocketRobz/TWiLightMenu#316]
So i have no idea if this is even feasible but it would be great if we can get GBA link support for games that use it such as pokemon, especially considering that it's the only way to migrate from gba roms on the 3ds.

**Comment by yamakachat** [comment]
Hey!!
I have the same problem: pokemon ruby ou emerald doesn t want to run with gbarunner. Do you find how to ?

**Comment by piratesephiroth** [comment]
I don't think that's the same problem though. Also gbarunner2 is [a different project](https://github.com/Gericom/GBARunner2).

**Comment by yamakachat** [comment]
Gbarunner2 is included with twilight menu++ , i put bios.bin in root .
I can play some gba game but i can’t play with pokemon emerald pokemon ruby and pokemon saphir. Did someone get a fix?

**Comment by RocketRobz** [comment]
Your issue is different from the one @Shinigati is having.
Also, this is a GBARunner2 issue, not a TWLMenu++ issue.
If you have an issue related to GBARunner2, please post it in the issue tracker in the link @piratesephiroth posted.

**Comment by flutterbrony** [comment]
I tought it was moving, and we will be able to launch a ds rom with a gba slot-2 rom emulated :x

Anyway, is it possible to do something like the snes ramdisk for it to work ? (Just a stupid thought I just had, maybe the issue is not this, but more how to emulate the slot-2 :/)

**Comment by NightYoshi370** [comment]
No it is not possible, due to GBA roms not fitting the 3MB limit

**Comment by NightYoshi370** [comment]
Wait, does this have anything to do with TWiLightMenu++ at all?
