### ISSUE TITLE
A little "issue"

### ISSUE THREAD

**Issue by Valkristh** [RocketRobz/TWiLightMenu#321]
Hello I've just downloaded the last update and I noticed a change in "cfw - sdnand root" folders, so now I have 2 TWiLight Menu++ icons, I know what to do for delete the older one, but some people maybe not... 
Maybe in "what's new" you can put the instructions for doing that

**Comment by RocketRobz** [comment]
It's placed above `What's new?`.

**Comment by Valkristh** [comment]
I forgot to tell, I launch it from hiya
