### ISSUE TITLE
7.0.0/7.1.0 Luma3DS 11.9.0 Black Screen

### ISSUE THREAD

**Issue by bandreghetti** [RocketRobz/TWiLightMenu#329]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

TWiLight Menu++ Launcher was deprecated in 7.1.0

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[7.1.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

TWiLightMenu++ runs after touching its HOME Menu icon.

### Actual behaviour

After touching the HOME Menu icon, I get a black screen. It stays that way if I do nothing and returns to the HOME Menu if I press any button.

### Steps to reproduce

1. Copy `_nds` folder and `boot.nds` to the SD card
2. Install TWiLightMenu++ 7.1.0 `.cia`s on an Old 3DS XL running Luma3DS+boot9strap v11.9.0
3. Run TWiLightMenu++ from HOME Menu icon

### Additional details

I tried installing 7.0.0 too, which still used TWiLightMenu++ Launcher, and although the launcher did run, when I touched the button "Run TWiLightMenu++" I got the same response as I'm getting with 7.1.0

**Comment by david4444** [comment]
I don't know much about this, but as it seems, your DS mode is bricked.
Go into the Download Play application and go to Nintendo DS. Wait about 10 seconds.
If it doesn't boot, it's bricked and can be unbricked using this:https://3ds.hacks.guide/troubleshooting
and go to "DSi / DS functionality is broken after completing the guide" and follow the instructions.
If it boots, then again i don't know much about this and i can't help.

**Comment by bandreghetti** [comment]
@david4444 you were absolutely correct. I didn't know about this issue. Maybe a note on the wiki page on How To Install would be a good idea? Anyway, thanks!
