### ISSUE TITLE
Rebuild SnemulDS from sources for twlm++

### ISSUE THREAD

**Issue by 1upus** [RocketRobz/TWiLightMenu#334]
Hi, I’m found some sources here:
https://github.com/cotodevel/SnemulDS/
And some updates here:
https://coto88.bitbucket.io/

Maybe its possible to rebuild it for twlm++ and run snes roms directly from menu like nes and gb/c?

**Comment by RocketRobz** [comment]
afaik, this can't read from the SD card, so that's why we went with RAM disk for SNEmulDS.
