### ISSUE TITLE
7.2.0 break Pokémon Platinum and Pokémon Black 2/White 2 (with AP)

### ISSUE THREAD

**Issue by Plausible0Bug** [RocketRobz/TWiLightMenu#336]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Release _[v7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[v7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

The game should boot.

### Actual behaviour

Stuck on white screen

Tell us what happens instead

### Steps to reproduce

1. Launch v7.2.0 Twilight Menu and try to boot Pokémon Platinum and Pokémon Black 2/White 2 (with AP)
2. The screen will turn white

Additional investigation:

By manually reverting the nds-bootstrap version back to 15 (v7.2.0 came with nds-bootstrap 16) I can boot into Pokémon Black 2 but not Pokémon Platinum.

By reverting everything, include _nds folder and installed cia back to those of v7.1.0 everthing start to work again.

I guess it is related with both nds-bootstrap and the Twilight menu.

**Comment by RocketRobz** [comment]
It's just related to nds-bootstrap.
Make sure you aren't the game in DSi mode.
With DS mode, it works fine for me.

**Comment by Plausible0Bug** [comment]
Hi,

I can confirm even after a clean setup (_nds folder removed and cias uninstalled) and start from the wizard where it ask me my console model, I cannot boot following nds rom:

3541 - Pokemon Platinum Version (US).nds
MD5: F8905424F7D8AEA299C51EC7580B33D8

I can confirm the default setting of Twilight menu is DS mode instead of DSi mode.

**Comment by Plausible0Bug** [comment]
@RocketRobz 
Hi,

I tried the TwiLightMenu 7.2.0 on another 3DS with Luma3DS installed and was able to reproduce the problem.

**Comment by RocketRobz** [comment]
I have no idea what's wrong, because it works just fine for me with TWLMenu++ v7.2.0 and nds-bootstrap v0.16.0.
It's possible your ROM got corrupted.

**Comment by Plausible0Bug** [comment]
@RocketRobz Sorry for keep bothering you, but could you please kindly share the hash of Pokemon Platinum Version (US) ? Hopefully I can get my hand on another rom that is not corrupted and keep using my save file.

**Comment by RocketRobz** [comment]
Mine is `C779CA1023D943D06F71975257626186`

**Comment by Plausible0Bug** [comment]
Thanks I'll give it a try.
