### ISSUE TITLE
Remove filename in the delete/per-game configuration menu

### ISSUE THREAD

**Issue by RS55** [RocketRobz/TWiLightMenu#339]
What the title says, in the menu to eliminate game and options per-game seems to me that it's over. Ex: "Kingdom Hearts 358-2 Days (USA).nds" is even out of the text box.

I'd say it's just aesthetic, but in the case of the per-game options it would give more space to the visual, besides that the banner is already displayed in the same menu next to the icon

**Comment by NightYoshi370** [comment]
What theme are you talking about?

**Comment by RS55** [comment]
DSi and 3DS of course, the other themes are faithful.

**Comment by NightYoshi370** [comment]
Maybe we can make it so long file names aren't shown? That'd solve your issue

**Comment by arraystock** [comment]
@RS55 Can you try the latest nightly and see if that has appropriately fixed your issue?

**Comment by arraystock** [comment]
This can probably be closed.
