### ISSUE TITLE
An error has occurred after installing and running latest cia

### ISSUE THREAD

**Issue by Cee123** [RocketRobz/TWiLightMenu#341]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Release  7.2.0
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release 7.2.0
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

It should load straight into Twilight Launcher ++.

### Actual behaviour

Black screen and
"An error has occurred.
Press and hold the POWER button
to turn the system off.
Please refer to the Operations
Manual for details"

Note: I dont receive this error when using an earlier version of the .cia launcher files. But then it shows as an older version of Twilight Menu ++ without any of the new features.

### Steps to reproduce

1. Download latest release - 7.2.0
2. Copy both BOOT.NDS and Boot_fc.nds to the root of the card
3. Copy _nds to the root of the card
4. Copy "Twilight Menu - Game Booter.cia" and "Twilight Menu.cia" to the cias folder
5. Install both cias with FBI
6. Run TWilight Menu++ icon - Black screen and error message

**Comment by piratesephiroth** [comment]
You don't need the boot.nds and boot_fc.nds on the root of the SD on the 3DS.

Just the copy the _nds folder and install the CIAs

**Comment by Cee123** [comment]
I tried with just Boot.nds at the root of the card. Same error. So then I tried deleting both boot.nds and boot_fc.nds from the root. Then launching it again, same error.

**Comment by Volti-p** [comment]
Which Error do you exactly get?

**Comment by piratesephiroth** [comment]
Do other DS games and apps work?
(like download play)

**Comment by piratesephiroth** [comment]
Perhaps it's a configuration file or something.
Try to delete the old _nds folder.

**Comment by Cee123** [comment]
Well, I found out the problem was - I installed twilight menu ++ on the emunand while still having dsimenu++ installed on the actual nand. I uninstalled the old version on the real nand and installed twilight menu ++. Now it works on the emunand as well. My mistake.

**Comment by Cee123** [comment]
You were right the old files were still there. /facepalm haha
