### ISSUE TITLE
Only the first five enabled cheats work

### ISSUE THREAD

**Issue by Antonio231102** [RocketRobz/TWiLightMenu#344]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _[2.1.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

All enabled cheats should be loaded into the game.

### Actual behaviour

Only the first 5 enabled cheats on the list are actually loaded.

### Steps to reproduce

1. Have at least 6 cheats added for a game.
2. Enable at least 6 cheats.
3. Load the game. You will notice only the first 5 cheats you enabled will actually work.

**Comment by Epicpkmn11** [comment]
Yeah, this is an nds-bootstrap issue, I'm pretty sure TWiLight will load all the cheats into `sd:/_nds/nds-bootstap.ini`, but nds-bootstrap has a limit on how many codes it can do
