### ISSUE TITLE
Manually set path to nds-bootstrap.nds

### ISSUE THREAD

**Issue by TomSputz** [RocketRobz/TWiLightMenu#345]
It would be nice to have this in the UI instead of needing to use a file manager to rename them - its handy for easily downgrading to versions of bootstrap which have features which were broken in later releases.

**Comment by NightYoshi370** [comment]
@TomSputz Actually, scratch the question above. I'll reword it:

Expect for Unlaunch with no HiyaCFW support in 11.X, what works in an older version that no longer works in the latest version?

Also, if this ever gets implemented, the person that implements it will need to make sure that the .nds file is actually nds-bootstrap and not some MKDS rom or something. That alone, will cause many troubles as there is no guaranteed & reliable way that you can tell that it's a nds-bootstrap file. There are different build environments supported with nds-bootstrap (RocketRobz libnds fork and the official libnds), different file sizes per compiling, and so much more things.

If you don't do these checks, it would lead for a bunch of uninformed people accidentally setting a game as nds-bootstrap and then making a bunch of issues on it in the Issue page on Github. There are also other issues, and with all that, I don't think this suggestion should be implemented at all.

I'll leave the rest of this up to Robz and co.
