### ISSUE TITLE
An error has occured

### ISSUE THREAD

**Issue by Dragonhead247** [RocketRobz/TWiLightMenu#349]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x ]  Release _[7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour
Runs app

### Actual behaviour

Get to menu, bring up nds start screen, I tap to open and it tells me to hold the power button to shutdown

### Steps to reproduce

1. Installed all cias and folders
2. Ran the app
3. No profit. Only error message

**Comment by RocketRobz** [comment]
The launcher is no longer needed. Just open the app in the 3DS HOME Menu.
