### ISSUE TITLE
How to make a .img file [HEEEEEEEEELP! ]

### ISSUE THREAD

**Issue by jonaz8** [RocketRobz/TWiLightMenu#350]
I apologize for the inconvenience but..........

i have the RAMDisk but i don´t know how to create the file

**Comment by RocketRobz** [comment]
Instructions are here, in the SegaMD/SNES tab.
https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/

**Comment by jonaz8** [comment]
thanks :) good evening

**Comment by piratesephiroth** [comment]
regarding that tutorial, the disk label is not relevant though
