### ISSUE TITLE
question about launcharg support

### ISSUE THREAD

**Issue by flutterbrony** [RocketRobz/TWiLightMenu#351]
I saw your commit e719839 about the removing of buggy .launcharg, does that mean it will not be possible to use launcharg anymore ?

**Comment by RocketRobz** [comment]
Yes.

**Comment by flutterbrony** [comment]
Ok, thanks, so I have to upgrade to the latest version of unlaunch now. Do you know if there is any issue with it for some dsiware ? (like using system settings, ds browser, dsishop, or anything) ?

**Comment by NightYoshi370** [comment]
Please ask questions like these on our GBATemp thread. This is a place for issues and suggestions, not discussions. Besides, you can get much quicker answers there.
