### ISSUE TITLE
Some Games Freeze After Cheats are set

### ISSUE THREAD

**Issue by Night152** [RocketRobz/TWiLightMenu#352]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [X ]  Release _[7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ X]  Release _[7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Games should launch with cheats activated and able to use.

### Actual behaviour

For some games (such as Pokemon Black/White 2), after cheats are set in the pre-launch menu, the game freezes at a white screen when attempting to launch. This only occurs after cheats are set. The games used to launch fine prior to the cheat application.

In the case of Pokemon Black/White 2, they have been AP-patched when this was tested.

### Steps to reproduce

1. Select cheats to activate for Pokemon Black/White 2
2. Attempt to launch game.

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWiLight issue.
