### ISSUE TITLE
date and time on TWiLightMenu++

### ISSUE THREAD

**Issue by flutterbrony** [RocketRobz/TWiLightMenu#355]
Just wanted to know if it's already implanted ? I thought I may do that, so I did some dummy homebrew to test many ways to display date and time on the ds, then I wanted to see how it could be added to the dsi theme of TWiLightMenu++, and I saw some code related to date and time in romsel_dsimenutheme/arm9/source/ date.cpp and date.h wich seem to already be able to do that.

**Comment by NightYoshi370** [comment]
Isn't this a clone of #102?

**Comment by flutterbrony** [comment]
Not really, but I could have asked there yes, it would avoid openning another issue just for that.

I just wanted to know if it was already done, because I saw the some code that seem to handle date and time, but it still doesn't print it on the screen of the dsi.

**Comment by NightYoshi370** [comment]
It is not implemented yet. Please use #102 for future conversation regarding this topic.
