### ISSUE TITLE
Cheat Menu crashes TwilightMenu 3/4 of the time

### ISSUE THREAD

**Issue by FM1337** [RocketRobz/TWiLightMenu#356]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration
Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ x]  Release _[the one that came with the twilightmenu 7.2.0 release]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [ x]  Release _[7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Pressing Y on the AceKard menu to bring up options and then pressing cheats or pressing X should bring up the cheat menu

### Actual behaviour
Sometimes it works, other times it'll crash to the power off mode in 3DS mode or it'll cause a red crash screen on the top screen 

### Steps to reproduce

1. Launch TwilightMenu
2. Go to a game with cheats
3. Press Y to open up the context menu for that game
4. Press Cheats (or Press X)

**Comment by FM1337** [comment]
After doing some investigation, it only appears to be happening with White 2 after AP patching it, Also trying to start it also seems to be crashing twilightmenu as well.

**Comment by FM1337** [comment]
So it appears the culprit is my usrcheats.dat file hmm

**Comment by NightYoshi370** [comment]
Where have you gotten that usrcheat.dat file from?

**Comment by FM1337** [comment]
https://gbatemp.net/threads/deadskullzjrs-flashcart-cheat-databases.488711/
and I modified it using the r4 cheat editor to remove everything but
Pokémon games

**Comment by NightYoshi370** [comment]
I'm no expert on how this works, but can you try using the default one with no modifications and see if it works?

**Comment by FM1337** [comment]
I had tried it with the default one, but it also suffered the same problem
so I trimmed it down because I thought the issue was it was too big (36MB)

**Comment by NightYoshi370** [comment]
Have you tried completely removing your _nds folder and redownloading it from the repo?

**Comment by FM1337** [comment]
Before the new version was released yes

**Comment by NightYoshi370** [comment]
Want to try the same thing for the new release? After all, we did change a lot of things relating cheats

**Comment by FM1337** [comment]
Sure give me like 30 minutes

**Comment by FM1337** [comment]
yeah it still happens

**Comment by FM1337** [comment]
after redownloading the usrcheat.dat it appears to fix the one issue I was having but now I'm having a different one (white screen with white 2), this may be a nds-bootstrap issue, but none the less it isn't related to twlightmenu++ so this can be closed
