### ISSUE TITLE
Failed to install "TWiLight Menu" after removing DSiMenu++

### ISSUE THREAD

**Issue by miniluigi008** [RocketRobz/TWiLightMenu#358]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Release _[v2.1.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Unexpected behaviour

I haven't used my 3DS in a while so I was still using DSiMenu++ and decided to update. Everything seemed to be working OK until I got to installing the files for TWiLightMenu.

I was able to install the file "TWiLight Menu - Game Launcher" title (as it installs and shows in the DSi title list) but the other "TWiLight Menu" title gives a strange error in FBI, I even tried installing 7.1 instead of 7.2. Not sure what the issue is here as other homebrew titles install perfectly fine and I have plenty of space. I don't use anything other than sysNAND.

This is the error I get:

```
Failed to install CIA file.
Result code: 0xC8A08035
Level: Status (25)
Summary: Invalid state (5)
Module: AM (32)
Desc: <unknown> (53)
```

If it helps, I have used TWLoader as well, but I uninstalled the older DSiMenu++ and TWLoader with FBI.

Starting the TWiLightMenu Launcher without the file installed gives a "An error has occurred" black screen, as to be expected since it's missing files.

Any ideas as to why I can't install the one TwiLight Menu title? I spent about four hours before exhausting my options.

EDIT: Downloaded old version 6.8.2 and it installed. Is there something wrong with the 7.2 and 7.1 titles?

### Steps to reproduce

1. Download and replace _nds folder as usual, copy new cias to root
2. Attempt to install cias with FBI
3. Problem

**Comment by RocketRobz** [comment]
Try uninstalling some DSiWare titles before installing the TWLMenu++ CIA.

**Comment by miniluigi008** [comment]
@RocketRobz I have 7.0MB free for DSiWare.

**Comment by RocketRobz** [comment]
Uninstall a title anyway.

**Comment by miniluigi008** [comment]
@RocketRobz Copied DSiWare to SD, deleted it from system, retried 7.2 title install and it worked. Thanks for the suggestion.
