### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by MDHEXT** [RocketRobz/TWiLightMenu#360]
this is more of a question than an issue. i need instructions on how to use action replay cheats with this software. im using a Nintendo 3ds xl (2012) (old). please help as i am confused.

**Comment by Epicpkmn11** [comment]
Currently only the Acekard theme can enable / disable cheats. (the others will be able to in the next version)
If your using the DSi theme you need to tap the settings icon in the top left, then scroll down to `Theme` and press left/right until it's set to `Acekard`, then exit settings (press `B`). Then you need to go to the game to want to enable / disable cheats on, press `Y` to enter Per-game settings, then press `X` to enter the cheat menu

**Comment by NightYoshi370** [comment]
Since the latest version has been released, this can be closed. I'll be writing a guide to the wiki hopefully soon
