### ISSUE TITLE
crashed while ftp

### ISSUE THREAD

**Issue by vlmo** [RocketRobz/TWiLightMenu#361]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have: 

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi) 

luma 9.1

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version : NONE

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

Wanted to wireless connect my n3ds to pc to transfer files to n3ds

but instead its crashed when i tried to open the n3ds name on the network tab on my pc win10 
how can i upload my crash with DMP format?
thanks
 i hope i put in right post area 

### Steps to reproduce

1.
2.
3.

**Comment by NightYoshi370** [comment]
That is not a TWiLightMenu++ issue. That's an issue with the transfer tool.
