### ISSUE TITLE
L+R+DOWN+B Reset causes an error has occurred message (3DS)

### ISSUE THREAD

**Issue by ChampionLeake** [RocketRobz/TWiLightMenu#367]
When exiting a DS game in TWLMenu++ for the 3DS (Latest Bootstrap and game-patchinig enabled from luma's configuration menu), the 3DS instead gives "An error has occurred. Press and hold the POWER Button to turn the system off."

**Comment by legoj15** [comment]
For me, it just reboots back into the 3DS's OS instead of going back to TWiLightMenu

**Comment by RS55** [comment]
In my place generates the launch of Flipnote Studio on my DSi

**Comment by ChampionLeake** [comment]
@RS55 uhhh, what?

**Comment by RS55** [comment]
I have unlaunch 1.8, note that flipnote was selected in case of Load Error, put the launcher by default (only allows me the nand, not the SDNAND) and now when doing the combination I get the system error lol

**Comment by legoj15** [comment]
Latest TWiLightMenu & release bootstrap doesn't seem to have this issue anymore for me atleast

**Comment by NightYoshi370** [comment]
Also, isn't this a nds-bootstrap issue?
