### ISSUE TITLE
Acekard theme issues

### ISSUE THREAD

**Issue by RS55** [RocketRobz/TWiLightMenu#371]
Cheats menu (Black & Adv.Evo Themes) only shows selected item.

MHGen Theme: There are problems when pressing Start, when selecting system settings nothing happens for example, you can also start a game as if it were just a picture above the menu

That's all for now.

**Comment by NightYoshi370** [comment]
Is this issue even related to TWiLightMenu++ itself?
Shouldn't it go in the akmenu-theme repository that I made?

**Comment by NightYoshi370** [comment]
Should this be closed or nah?
