### ISSUE TITLE
GB (C) / NES when hiding folders

### ISSUE THREAD

**Issue by RS55** [RocketRobz/TWiLightMenu#38]
Add the possibility to change from NDS to GB(C) / NES when hiding folders. As it happened before using the button up or down

**Comment by ccccmark** [comment]
If I remember, you can put roms, different from NDS roms, at the same folder

**Comment by Robz8** [comment]
That's true.

**Comment by rodrigost23** [comment]
I think the issue is that it's not as organized as having the ROMs in different folders, and navigating through folders is not so much practical.

**Comment by Valkristh** [comment]
One solution a made is add gameyob and nesds to homescreen with dsiwares, so when the folders are hide i only see the nds roms

**Comment by NightYoshi370** [comment]
Actually, I got an idea for a solution.

In the discord server, we were discussing a select menu for the DSi theme. For one of the options, how about we add a view mode, where we can filter amongst the following:

- ALL
- DS (All)
- DS (Retail)
- DS (Homebrew)
- NES
- GameBoy
- SNES
- Master System
- Genesis

That could solve the problem, and all you need to do is just dump all your roms in the same folder

**Comment by FlameKat53** [comment]
also, to add onto what NightYoshi370 was saying, you can now move your games positions without renaming them, which means that `Up/Down` Are now used for that function

**Comment by NightYoshi370** [comment]
Now that view mode is in the latest commit, this can be closed now
