### ISSUE TITLE
usrcheat can cause game stop booting even when no cheat is enabled

### ISSUE THREAD

**Issue by Plausible0Bug** [RocketRobz/TWiLightMenu#387]
**Console:** New 3DS/2DS (XL) using Luma3DS
**TWiLight Menu++ version:** 7.3.0 rev1
**Expected Behavior:** The game should work as if no cheat is enabled.
**Actual behavior:**  When the usrcheat.dat is placed in extra folder the Pokemon platinum can stop booting, stuck on white screen forever.

### Steps to reproduce

1. Put usrcheat [(download)](https://gbatemp.net/threads/deadskullzjrs-flashcart-cheat-databases.488711/) to extra folder
2. Boot Pokemon platinum
3. Game will suck on white screen

**Comment by Plausible0Bug** [comment]
The following issue is actually related:

https://github.com/RocketRobz/TWiLightMenu/issues/336

The reason 7.2.0 is not working for me is also because I have usrcheat file.

Downgrading everything to 7.1.0 will make it work again because 7.1.0 does not support usrcheat.dat

To make things more interesting, it seemed nds-bootstrap file need to be removed along with the usrcheat.dat to make the game work again, obviously some configuration was written there to enable the cheat.

**Comment by NightYoshi370** [comment]
To further explain, the bug isn't that the game wasn't booting (that's a nds-bootstrap issue). Rather, it's that there is something written to nds-bootstrap.ini about the cheats even though none was enabled

**Comment by NightYoshi370** [comment]
@RocketRobz I have a feeling the latest commit you pushed is related to this. Is that correct?

**Comment by RocketRobz** [comment]
Probably.

**Comment by Plausible0Bug** [comment]
Hi, I'm still experiencing this on my new 3DS with the exactly same usrcheat file...
