### ISSUE TITLE
TWiLightMenu .3ds?

### ISSUE THREAD

**Issue by bobbyso** [RocketRobz/TWiLightMenu#399]
Hello, a question/issue: do I really need to install the .cia files?
Are there no possibility to have a .3ds file in order to insert it in the Homebrew Channel?

I have 
New 2DS XL
Luma3DS (11.9.0)

Sorry if I got the wrong section, I'm new to github ..

**Comment by RocketRobz** [comment]
Yes, the CIA files need to be installed.
It is not possible to have it as a .3dsx files, as this app is made as DSiWare.

**Comment by bobbyso** [comment]
Is a link within the Homebrew Channel possible?

**Comment by RocketRobz** [comment]
There was the TWiLight Menu++ Launcher, which was available as a 3DSX, but that got deprecated for an updater, as TWiLight Menu++ booted faster without a Launcher.
You can just launch TWiLight Menu++ from the 3DS HOME Menu. You won't get banned by doing it.
