### ISSUE TITLE
White screen when trying to launch any game.

### ISSUE THREAD

**Issue by Vaporeon** [RocketRobz/TWiLightMenu#403]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only Version 1.8
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release 7.3.0 Rev 1
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Start an NDS game

### Actual behaviour

Screen whites out after the loading animation completes

### Steps to reproduce

1. Install fresh copy on a DSi with only Unlaunch 1.8
2. Try run NDS title
3. Loading should fail

**Comment by Epicpkmn11** [comment]
Are you launching `TWLMENUPP` or `HIYACFW` in Unlaunch? You need to use `HIYACFW`.

**Comment by Vaporeon** [comment]
I don't have HIYA CFW installed
Just Unlaunch configured to load into TWLMENUPP directly
This worked before but I recently updated both unlaunch and TWLMENUPP and now it broke.
Does this not work anymore?

**Comment by Vaporeon** [comment]
Oh I see. Hopefully I still have the CFW files somewhere. Is support for that ever coming back?

**Comment by Epicpkmn11** [comment]
It might, but I don't think anyone really knows exactly what's causing it to not work without Hiya currently

**Comment by NightYoshi370** [comment]
I don't think this is related to TWiLightMenu++
