### ISSUE TITLE
Dragon Ball Z Supersonic Warriors 2 wont working

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [RocketRobz/TWiLightMenu#405]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v7.3.0 (Rev 01)]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

the game starting but it says insert gamecard

### Steps to reproduce

1. 
2.
3.

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWiLight Menu++ issue.
