### ISSUE TITLE
Add order games by file type

### ISSUE THREAD

**Issue by RS55** [RocketRobz/TWiLightMenu#406]
What the title says Since it was added the feature of hide or show the games of each console, to improve the order given that the NDS have their own icons and those of each console emulated their own.

Adding an option "by type" in the same order as they appear in the Filetype Settings menu, I do not think it's a problem since that way you would not see all the games mixed as a salad.

Therefore ... I would say something like this in the DSi menu for example:
NDS - NES - GB/C - SegaMS - SegaMD - SNES

It's just an idea, so they're free to discard!

**Comment by NightYoshi370** [comment]
Maybe we can do a "reset order" button, where it can ask us how it wants it to be reset: alphabetically or by console. This would make much more sense in my opinion.

**Comment by RS55** [comment]
Better yet then.

**Comment by RS55** [comment]
Better said impossible.

**Comment by NightYoshi370** [comment]
better said impossible? What?

**Comment by RS55** [comment]
My mistake, is an expression in my language. What you said is much better.

**Comment by NightYoshi370** [comment]
Alright, so there has been new sorting options added. However, file types is not one of them, so we'll be keeping this open
