### ISSUE TITLE
Home icon/hotkeys reboot to sysnand

### ISSUE THREAD

**Issue by wzhy90** [RocketRobz/TWiLightMenu#408]
### Your console

Tell us which console do you have:

- [ ✓ ]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi: 

- [ ✓ ]  Unlaunch_1.8+HiyaCFW_lasted

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ✓ ]  Release _ 7.3.1_r1

### Expected behaviour

Tell us what should happen
tap home icon/hotkeys go-to sdnand's launcher before unlaunch 1.8 released.

### Actual behaviour

Tell us what happens instead

after unlaunch 1.8 released and some version of twlmenu released, reboot will go-to the sysnand's launcher.

### Steps to reproduce

just tap the home icon in twlmenu then it will goto sysnand

**Comment by RocketRobz** [comment]
This is an actual feature, not a bug.
