### ISSUE TITLE
Cheat menu refuses to show after pressing X in the sub-game menu

### ISSUE THREAD

**Issue by ChampionLeake** [RocketRobz/TWiLightMenu#411]
Title says it all.

**Comment by RocketRobz** [comment]
Still shows for me.

**Comment by ChampionLeake** [comment]
Lucky. Idk why I get these problems

**Comment by arraystock** [comment]
The menu shows for me as well.

**Comment by coolmccoolsons** [comment]
probably theres no cheats for that game

**Comment by NaturalHarmonia** [comment]
I'm using the latest version of TwiLightMenu++ and when I move the cursor to Fire Emblem: New Mystery of the Emblem and press the Y-button to open the menu and then press X to try and use cheat codes nothing happens. No menu pops up. This doesn't happen with other games I have. Is anyone else experiencing this with this game?

**Comment by NightYoshi370** [comment]
@ChampionLeake can you please be more specific?

You haven't mentioned what game you're attempting.
You haven't mentioned where you got the cheats from.

We need this information in order to properly debug your issue.

**Comment by NightYoshi370** [comment]
@NaturalHarmonia Are you sure the game has any cheats?

**Comment by NaturalHarmonia** [comment]
> @NaturalHarmonia Are you sure the game has any cheats?

I've seen cheats for it on the internet. I went to [DeadSkullzJr's thread](https://gbatemp.net/threads/deadskullzjrs-flashcart-cheat-databases.488711/) on gbatemp and placed the usrcheat.dat in the extras folder. I don't know how to insert the cheats if the cheats haven't been placed in the usrcheat.dat or whatever.

**Comment by ChampionLeake** [comment]
@NightYoshi370 I posted a video link of the bugs/glitches I've been having with TWiLightMenu++ in the TWL Mode Hacking discord server.

I'll post it here: https://youtu.be/6M3GntG9yvE

**Comment by NightYoshi370** [comment]
Please don't make an issue here and then talk about it *only* in the discord server.

a) Discord is a really bad chatting platform that needs to get wiped off the planet
b) Not everyone is in the discord server (myself included), so they won't see your messages
c) If you make an issue on github, you should add the details *on github*.

Well, either way, have you downloaded the cheat file from DeadSkullzJr's thread? If so, then it'd be nice if you showed me the MD5 hash of the usrcheat.dat file, so I can make sure we have the same one.

**Comment by ChampionLeake** [comment]
a) There's nothing wrong with discussing the issues/problems other users with with a homebrew application in multiple platforms. And don't assume that I _**only**_ talked about it in the Discord server.
c) I made my own cheat database and used DeadSkullzJr's cheat file to have the same issue. I don't have his cheat database but do you still want the MD5hash of mine?

**Comment by NightYoshi370** [comment]
1a) There is, because you talk about an issue on one platform but put other important details in others. This ties in with my previous B statement.
1b) Well, it seemed like it. "Oh! Here's an issue I'm putting on github! Nah, no need to worry about the details: You can find it on derpcord!"

Uh, anyways, to your `c`, do you mind trying again with the DeadSkullzJr's cheat file? As far as I'm seeing it, the cheat database works on TWiLightMenu++ just fine, and all the other issues that have arrised have used a modified one.

**Comment by ChampionLeake** [comment]
1a-II) I can understand the detail part. When it first occurred for me, I right away reported it here. I went on the discord to talk about it to see if anyone else had the same issue. Someone mentioned having the same issue and many others. So I made a video to compare if the same results happen to them. Of course,you would've known this is you were on the server but it doesn't matter as the information is being provided here.
1b-II) I'd confirm that it wasn't in that way. Of course, you just wanted more information which was provided.

And you seemed to be correct about the DeadSkullzJr cheat data base. I had 2 other DeadSkullzJr cheat database files. 1 that was outdated, 1 that's updated, 1 that's modified. Of course, the outdated cheat database seemed to have caused more of the issues including the modified cheat database. So, those are now long gone and things work perfectly fine. 

SO easy fix is to just use DeadSkullzJr's cheat-database and stay up-to-date with it.

**Comment by Nomelas** [comment]
Happens for me on dsi theme while acekard theme works

**Comment by arraystock** [comment]
@ChampionLeake please try the build I posted in #442.

**Comment by arraystock** [comment]
This issue can be closed.
