### ISSUE TITLE
Twilight menu ++ doesn't load save

### ISSUE THREAD

**Issue by littlelum** [RocketRobz/TWiLightMenu#417]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by FlameKat53** [comment]
Can you give a bit more information?

**Comment by littlelum** [comment]
For some reason, it recognizes the fact that the save exists, (because it doesn't create a new one) but the actual save progress doesn't load. Sorry for the lack of information, I accidentally hit "post" too early.

**Comment by littlelum** [comment]
The save is in the "save" folder, too, @FlameKat53

**Comment by FlameKat53** [comment]
“Save” or “Saves”?

**Comment by FlameKat53** [comment]
try saving at a point in the game you can recognize, and see if it loads

**Comment by littlelum** [comment]
"saves" the exact capitalization, too, in the same directry as the rom itself

**Comment by FlameKat53** [comment]
what game is it exactly?

**Comment by littlelum** [comment]
I tried that, it didn't load that.

**Comment by littlelum** [comment]
Warioware diy. I'm trying to inject a boss microgame in there.

**Comment by FlameKat53** [comment]
Currently that game can’t save, also this is a problem with nds-bootstrap btw

**Comment by littlelum** [comment]
Ok

**Comment by littlelum** [comment]
thanks for replying

**Comment by FlameKat53** [comment]
I’m glad you got the information you would need so your problem wouldn’t go on as a myster

**Comment by RS55** [comment]
I suffer from a problem regarding the Saves, certain games load me Saved from my Cartridges like Kingdom Hearts 358/2 Days and Mario Kart DS but there are others like Pokemon Blue Rescue Team and Pokemon Guardian Signs that do not load me the Save (when it was TWLoader it did it without problem) and a new one is created from Zero ... Any idea?

**Comment by RocketRobz** [comment]
Starting with v6.8.3, TWiLight Menu++ now reads .sav files from the `saves` folder, which is in the exact same folder as the .nds ROMs.
Move your existing .sav files in the .nds folder, to `saves` folder.

**Comment by RS55** [comment]
@RocketRobz Hey but in my case it's not a location problem, it just does not read the .sav and when it was TWLoader if it did, that is, a long time ago. I open a separate topic or something?

**Comment by RocketRobz** [comment]
Yes. Open a new issue at nds-bootstrap's repo.

**Comment by cryopotato** [comment]
what if the .sav is already in the "saves" folder? literally all my other games work except animal crossing. (im using the latest versions of unlaunch, hiya and tlight.)

**Comment by blacklazarus** [comment]
Los juegos de NDS si me guarda los saves, pero consolas retro como SNES no crea ningún save. No se puede guardar avance en consolas retro
