### ISSUE TITLE
Pong loading screen isn't random

### ISSUE THREAD

**Issue by david4444** [RocketRobz/TWiLightMenu#418]
Basically the Pong loading screen has a set path. You can memorize it.
I know this is dumb.

- [*]  Old 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [*]  Luma3DS

### TWiLight Menu++ version

Tell us which versions you are using:

- [*]  nds-bootstrap ver Release v0.17.1 TWiLightMenu 7.4.0

### Expected behaviour

Tell us what should happen
The Pong ball should bounce randomly

### Actual behaviour

Tell us what happens instead
The Pong ball bounces in a set path and can be memorized

### Steps to reproduce

1. Go into TWiLightMenu's settings.
2. Go into Games and Apps settings
3. Change Loading screen to "Pong"
4. Launch a game 2 times and watch the ball's path.

*If this is intentional or just dumb, just close this issue*

**Comment by NightYoshi370** [comment]
Well, I could probably try to make it randomized, though here's the thing: It is not an issue with TWiLightMenu++, as TWLMenu doesn't handle loading screens. nds-bootstrap does.

Closing due to irrelevancy
