### ISSUE TITLE
Problem in hidden folders mode

### ISSUE THREAD

**Issue by RS55** [RocketRobz/TWiLightMenu#43]
When hiding folders is enabled, for example, in NES games when trying to change only between DSiware and NES, the same with any folder, i think you should add something that is restricted to only those three folders (gb, nds and nes) together with the DSiware shortcut or something like that hahaha. Ironically, it is linked to a request (#38) I made a while ago...

**Comment by NightYoshi370** [comment]
Well, that's assuming that the users have roms in a `gb`, `nds` and `nes`.
What if I put it in a folder like `/gaming/Handheld/Nintendo/gameboy` and one in `/gaming/Console/Nintendo/NES`?
We could, theoretically just have folder buttons, but there's, like, no point to that.
I suggest that the roms be in one folder and have categories, like what I suggested in the discord server.

**Comment by NightYoshi370** [comment]
Actually, yeah, due to the inconsistencies with user setups and considering there's no point considering that you could just put the roms in one folder and change the views, I'll be closing this
