### ISSUE TITLE
Download DS crashes

### ISSUE THREAD

**Issue by lpla** [RocketRobz/TWiLightMenu#434]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly  9c343b4

### Expected behaviour

Open "Download DS" option (next to disabled Pictochat) in default theme.

### Actual behaviour

3DS crash: An exception occurred...

### Steps to reproduce

1. Open you vanilla/clean installed TWiLightMenu++
2. Open "Download DS" next to disabled Pictochat
3. Crash

(if this feature is not expected to work, as Pictochat, it should be disabled)

**Comment by RocketRobz** [comment]
Enable game patching in Luma settings.
