### ISSUE TITLE
Cheat error

### ISSUE THREAD

**Issue by MDHEXT** [RocketRobz/TWiLightMenu#440]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Cheats menu should open when pressing y then x

### Actual behaviour

Menu doesn't open and immediately closes back to emu options menu

**Comment by RocketRobz** [comment]
What's the issue, exactly?

**Comment by FlameKat53** [comment]
This is a literally useless issue, the only info is two words :/

**Comment by MDHEXT** [comment]
Whoops, accidentally left it blank.

**Comment by MDHEXT** [comment]
It's been edited

**Comment by FlameKat53** [comment]
I hope I didn’t seem rude, thank you for providing the needed info

**Comment by MDHEXT** [comment]
It ok, it was my mistake

**Comment by RocketRobz** [comment]
What game did you try it with?

**Comment by MDHEXT** [comment]
I tried it with all my games, but I only got the cheat menu to open in the acekard theme

**Comment by FlameKat53** [comment]
You are on v7.4.0 correct?

**Comment by MDHEXT** [comment]
Also, nice to know they aren't emulated, but then if that's true then I don't know what all the options are whenever you press y.

**Comment by MDHEXT** [comment]
I'm on the latest release

**Comment by MDHEXT** [comment]
I think 7.4.1?

**Comment by RocketRobz** [comment]
Yes, v7.4.1.

**Comment by FlameKat53** [comment]
can you install the updater? then click the button that is labeled “cheats”
# ![img](https://raw.githubusercontent.com/TWLBot/Builds/master/TWiLightMenu%20Updater/TWiLight_Menu%2B%2B_Updater.png)

**Comment by MDHEXT** [comment]
I've already done that

**Comment by FlameKat53** [comment]
ah

**Comment by MDHEXT** [comment]
Not sure why this doesn't happen on the acekard theme though

**Comment by arraystock** [comment]
@MDHEXT please try the build I posted in #442. Does it solve your issue?

**Comment by FlameKat53** [comment]
Hey, can this issue be closed, as it seems to be fixed?

**Comment by somedudeee** [comment]
Hi

**Comment by somedudeee** [comment]
Hi

**Comment by somedudeee** [comment]
Hi

**Comment by Volti-p** [comment]
don't spam.

**Comment by somedudeee** [comment]
Hi

**Comment by somedudeee** [comment]
Hi

**Comment by somedudeee** [comment]
Hi

**Comment by somedudeee** [comment]
Btw i love u 2 guyz

**Comment by somedudeee** [comment]
I wanna kiss u and jack u off

**Comment by somedudeee** [comment]
Pull me off

**Comment by somedudeee** [comment]
Go to xxx.com

**Comment by MDHEXT** [comment]
Uhh, was that me??? Or are all of these modifications someone else's???

**Comment by RocketRobz** [comment]
@MDHEXT Someone was spamming for no reason. :P

**Comment by NightYoshi370** [comment]
@somedudee please stop pulling a Daniel, and stop spamming ffs.
