### ISSUE TITLE
new cellphone couldn't login lantern

### ISSUE THREAD

**Issue by Alierchen** [RocketRobz/TWiLightMenu#441]
my new cellphone couldn't login Professional lantern , we used other phone to authorize it , but no useful .

put email address , also no code received . 

all version are the latest 

what's wrong ?

**Comment by FlameKat53** [comment]
How is this related to twilight menu++ at all?

**Comment by Alierchen** [comment]
> How is this related to twilight menu++ at all?

can you speak Chinese ?

**Comment by FlameKat53** [comment]
No, I cannot speak Chinese, i’m Sorry for the inconvenience

**Comment by FlameKat53** [comment]
Google Translate:

你好，有什麼問題？

**Comment by Alierchen** [comment]
> No, I cannot speak Chinese, i’m Sorry for the inconvenience

are you lantern service worker ?

**Comment by FlameKat53** [comment]
no?

**Comment by FlameKat53** [comment]
I don’t know what a “lantern service worker” is

**Comment by Alierchen** [comment]
service staff for lantern

**Comment by FlameKat53** [comment]
Can you link me to said “Lantern”?

**Comment by RocketRobz** [comment]
I'm sorry, but what issues are you having with TWiLight Menu++?
(And in case you ask, no I don't speak Chinese either.)

**Comment by Alierchen** [comment]
couldn't

**Comment by Alierchen** [comment]
my Lantern couldn't use Professional version

**Comment by RocketRobz** [comment]
Closing. Whatever issue you are having is not related to TWiLight Menu++.

**Comment by FlameKat53** [comment]
This is a lantern
https://www.athome.com/dw/image/v2/AAYZ_PRD/on/demandware.static/-/Sites-AtHome/default/dw1fce0782/images/124250975.jpg?sw=1268&sh=1992&sm=fit

**Comment by Alierchen** [comment]
not VPN ?

**Comment by FlameKat53** [comment]
May I ask to see a picture (photo) of what you are looking for?

**Comment by FlameKat53** [comment]
Is it this? 
https://getlantern.org/en_US/index.html

**Comment by piratesephiroth** [comment]
yeha, I think it's that

**Comment by piratesephiroth** [comment]
so I suppose he should be asking questions at their repository, not here
https://github.com/getlantern/lantern

**Comment by XD-Daniel-XD** [comment]
umm, this issue is obviusly clear. i don't get why people don't understand it. he clearly is reporting that if he selects Chinese language on TWLMenu++ settings a lantern will appear on his screen. smh










(this message is a joke. please don't kill me for that)
