### ISSUE TITLE
Going to the cheats menu sends you back if you press X too long.

### ISSUE THREAD

**Issue by david4444** [RocketRobz/TWiLightMenu#442]
This happens since the X button is also the return button.

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release 7.4.1
- [ ]  Nightly 

### Expected behaviour

When pressing the cheats menu, there should be at least a second where pressing X doesn't bring you back.

### Actual behaviour

If you press X and hold it too much, it will send you back to the per game options menu.

### Steps to reproduce

1. Go to the main menu of TWiLightMenu++
2. Press Y on any game
3. Hold X for about a quarter/half of a second to open the cheats menu.

EDIT:This doesn't happen with games that *DON'T* have cheats since the the button for back is B.
Note:I just found this by accident.  I probably just press buttons slowly.
you have to press quickly X to not return to the per game options menu.

**Comment by arraystock** [comment]
@david4444 Does this build solve the problem? (Use it to overwrite your `_nds` folder)
[cheat_hold_fix.zip](https://github.com/RocketRobz/TWiLightMenu/files/2897011/cheat_hold_fix.zip)
Also, if you can, test this under both DSi and R4 themes, as I believe this should fix it under both.

**Comment by david4444** [comment]
Testing right now.

**Comment by arraystock** [comment]
I figured, I just noticed the issue was present in the R4 theme as well.

**Comment by david4444** [comment]
Just tested. Sorry it took long. For some reason my PC was really slow with copying the _nds folder.
Anyways, it works. the issue is fixed in that build.

**Comment by arraystock** [comment]
No problem, glad it worked!

**Comment by ChampionLeake** [comment]
Yup, this fixed the issue. Thank you so much

**Comment by NightYoshi370** [comment]
Since this is fixed, I'll close it
