### ISSUE TITLE
Shortcut not working as intended

### ISSUE THREAD

**Issue by CapNinja** [RocketRobz/TWiLightMenu#461]
### Your console

Tell us which console do you have:

- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release 7.4.1

### Expected behaviour

Using the shortcut L+R+Down+B should send me to the Twilight Menu screen

### Actual behaviour

Close Twilight Menu instead

**Comment by RocketRobz** [comment]
This is an issue with nds-bootstrap, not TWLMenu++.
Also, the button combo won't always work, so the HOME Menu appears instead. It is currently unknown how to fix it.
