### ISSUE TITLE
Bright Control

### ISSUE THREAD

**Issue by CapNinja** [RocketRobz/TWiLightMenu#462]
Would be great if we have access to bright control inside Twilight Menu.

**Comment by RocketRobz** [comment]
You can already do that on the main menu screen, but not on 3DS or original DS, as it's not possible on those consoles.

**Comment by Epicpkmn11** [comment]
Also on DSi you can use Select + Volume Up/Down or on 3DS you can press Home, then (iirc) Start + D-Pad Up/Down to change brightness at any point.
