### ISSUE TITLE
Issue with DSi Menu when booting game from .argv file

### ISSUE THREAD

**Issue by Dragowolf33** [RocketRobz/TWiLightMenu#475]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlanch: Version 1.8. HiyaCFW: Not sure as I can't find it]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v0.17.1]_
- [ ]  Nightly _[279a9cc]_

### Expected behaviour
It should just boot to the game simple.
### Actual behaviour
Goes back to the DSi Menu on TwilightMenu++ top screen is white and the bottom screen is normal except when hovering over an icon it disappears. Also, there is no sound playing...
### Steps to reproduce

1. Go on to TwilightMenu++
2. Choose any game that is an .argv file
3. Result!

**Comment by RocketRobz** [comment]
.argv is not meant to be used to launch DSiWare.
It is meant to pass an argument to a homebrew.

**Comment by Dragowolf33** [comment]
> .argv is not meant to be used to launch DSiWare.
> It is meant to pass an argument to a homebrew.

How do I launch DSiWare then?

**Comment by RocketRobz** [comment]
You launch one as a .nds file, renamed from a .app file.

**Comment by Dragowolf33** [comment]
Oh. Thanks!

**Comment by Dragowolf33** [comment]
> You launch one as a .nds file, renamed from a .app file.

But would I need to rename the 000000## to a different name?

**Comment by RocketRobz** [comment]
> But would I need to rename the 000000## to a different name?

Yes.
