### ISSUE TITLE
 TWiLight Menu++ crashes when DS download play is opened

### ISSUE THREAD

**Issue by MasterGamingYT** [RocketRobz/TWiLightMenu#478]
TWiLight menu crashes when I try to launch DS download play, any help?

**Comment by RocketRobz** [comment]
If you're getting the Luma exception screen, turn on game patching in Luma settings.

**Comment by MasterGamingYT** [comment]
That fixed it, thanks

**Comment by RocketRobz** [comment]
No problem!
