### ISSUE TITLE
How do I return to Twilight menu

### ISSUE THREAD

**Issue by MasterGamingYT** [RocketRobz/TWiLightMenu#479]
I'm not sure how to exit the DS game I'm playing and return to twilight menu? (game patching on luma settings is enabled)

**Comment by NightYoshi370** [comment]
That's not an issue.
Also, L R DOWN (DPAD) B

**Comment by RocketRobz** [comment]
@MasterGamingYT If you have further questions, please ask in the GBATemp thread, one of the Discord servers, or the Rocket.Chat server.

**Comment by MasterGamingYT** [comment]
@RocketRobz Can you give me the link to the discord server?

**Comment by NightYoshi370** [comment]
You should join the Rocket.Chat server, as it isn't litered with discord's many issues.
Link can be found in the ReadME of the nds-bootstrap repository

**Comment by MasterGamingYT** [comment]
Ok
