### ISSUE TITLE
Can't open pictochat even with launcharg file

### ISSUE THREAD

**Issue by MasterGamingYT** [RocketRobz/TWiLightMenu#480]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [+]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [+]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [+]  Release _[7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen:
As long as you have the launcharg file, you can open pictochat anytime.

### Actual behaviour:
Even with the launcharg file, I can't open pictochat

Tell us what happens instead

### Steps to reproduce

1.Open twilight menu
2.Wait for it to load the main menu
3.CAN'T EVEN OPEN PICTOCHAT

**Comment by RocketRobz** [comment]
You need the actual Pictochat .nds file in `sd:/_nds`.

**Comment by NightYoshi370** [comment]
launchargs are dead. Just directly use the .nds file.

**Comment by MasterGamingYT** [comment]
@RocketRobz Am I safe to delete the 2 launcharg files in the rooms folder?

**Comment by NightYoshi370** [comment]
yes

**Comment by RocketRobz** [comment]
Yes.

**Comment by MasterGamingYT** [comment]
Ok thanks, also do I have to rename the pictochat to a specific file name

**Comment by RocketRobz** [comment]
Yes, `pictochat.nds`.

**Comment by MasterGamingYT** [comment]
Ok thanks

**Comment by MasterGamingYT** [comment]
When I open pictochat, it says:
"Communication error, the system will now shut down"
Any help?

**Comment by RocketRobz** [comment]
Change the TID at  hex offset 0xC in the .nds file to `HNEA`, using a hex editor.

**Comment by MasterGamingYT** [comment]
Which is the hex offset (I apologize if I sound dumb, I'm using mobile)
HEX Fragment
String
HEX Constant
DEC Constant
OCT Constant
Single precision
Double precision

**Comment by RocketRobz** [comment]
Hmm, no idea.

**Comment by MasterGamingYT** [comment]
Also when going to hex offset, do I have to put the x between the 0 and the C?

**Comment by RocketRobz** [comment]
No. Just put `C`.

**Comment by MasterGamingYT** [comment]
So I just put the c, and not the 0 or the x?

**Comment by RocketRobz** [comment]
Yes, that's what I said.

**Comment by MasterGamingYT** [comment]
What number do I put for HNEA

**Comment by RocketRobz** [comment]
`C` is a hex number.

**Comment by MasterGamingYT** [comment]
Is it 0d at number 00000068?

**Comment by RocketRobz** [comment]
I can't help you any further.
Anyone who knows how to use a hex editor on mobile may be able to help you.

**Comment by MasterGamingYT** [comment]
Oh ok
