### ISSUE TITLE
Game Menu Displaying Wrong Games/Crashing

### ISSUE THREAD

**Issue by MysticPenguin3** [RocketRobz/TWiLightMenu#482]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ x]  Release _[7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen
The list of games should show the icon for the game it loads. I should also be able to move games by pressing up on the dpad.
### Actual behaviour

Tell us what happens instead
My menu defaults to the same alphabetical layout everytime, with pokemon white 2 showing the icon for diamond and having no text. White 2 turns to black when i press up and it screws up the diamond icon. The icon changes when things move around. White 2 also wont launch.
### Steps to reproduce
I honestly dont know, but it happens every time for me.
1. Open TwMenu ++
2. Thats basically it, moving things around will change the icon and description. Resetting wont do anything. Moving games in some random orders will crash as well, but i cant seem to reproduce this

EDIT: here are some images of the issue
![image0](https://user-images.githubusercontent.com/47903355/53740752-e323c480-3e62-11e9-9752-4ed1c1aef7f1.jpg)

![image1](https://user-images.githubusercontent.com/47903355/53741078-92609b80-3e63-11e9-9e3e-2f765727d7b2.jpeg)
![image3](https://user-images.githubusercontent.com/47903355/53741083-94c2f580-3e63-11e9-9139-c95e1a115172.jpeg)
![image2](https://user-images.githubusercontent.com/47903355/53741092-9a204000-3e63-11e9-843c-aa4d5fd565ac.jpeg)

**Comment by arraystock** [comment]
Have you tried the latest nightly?

**Comment by MysticPenguin3** [comment]
No I haven't. Can you link that? I can't seem to find it

**Comment by Epicpkmn11** [comment]
TWiLight's latest nightlies can be found here:
https://github.com/TWLBot/Builds/releases

**Comment by MysticPenguin3** [comment]
https://mail.google.com/mail/u/0/?ibxr=0?ui=2&ik=90f5d0a7c2&view=att&th=16949389a407fc5b&attid=0.1&disp=inline&safe=1&zw This is what happened why I tried the latest nightly

**Comment by arraystock** [comment]
Do you have game patching enabled in Luma? (It might not change anything, I’m away from my 2DS so I can’t test) Also, if that doesn’t do anything, if you delete your TWiLight Menu configuration file does that make a difference?

**Comment by MysticPenguin3** [comment]
Game patching was already on, and deleting the config file resulted in the application crashing. I uninstalled and deleted every file I could find for TWL and reinstalled 7.4.1 fresh, and it fixed the issue I was having.

**Comment by arraystock** [comment]
Good! I’m glad you got it figured out.

**Comment by MysticPenguin3** [comment]
EDIT: I was able to recreate this bug by changing the loading screen theme to dark. The only way I have found to fix this is by deleting the application and the _nds folder, but it might just be a config file somewhere that I can't find.
