### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Karla02** [RocketRobz/TWiLightMenu#490]
Okay so I have a 2dsXL CFW but when I tried to install the .cia files nothing happened? NO GIFTS :(

**Comment by arraystock** [comment]
Please install [the updater](https://github.com/RocketRobz/TWiLightMenu-Updater/releases/tag/v3.0.0), and try to install TWiLight Menu through that. Also, if that doesn’t work, please provide more details about your system and how you tried to install the cia files.

**Comment by piratesephiroth** [comment]
There are no gifts because it's DSiWare. You have to reboot the 3DS or just press the power button once to close the home menu.

**Comment by FlameKat53** [comment]
Did your problem get resolved? (If so, this issue should be closed)

**Comment by RocketRobz** [comment]
Closing, due to no reply.
