### ISSUE TITLE
(Question) How do I install commits

### ISSUE THREAD

**Issue by MasterGamingYT** [RocketRobz/TWiLightMenu#493]
How do I install commits? When I download one, it's a zip file with just the source code.

**Comment by Epicpkmn11** [comment]
You can get automated builds from https://github.com/TWLBot/Builds/releases

**Comment by FlameKat53** [comment]
Hello, can you join the Rocket.chat server?
Link: ds-homebrew.serveo.net

You can be helped there much more easily, and you won’t need to open an issue every time you have a question.

**Comment by MasterGamingYT** [comment]
@Epicpkmn11 do I manually download the file, or install the nightly build using the updater

**Comment by Epicpkmn11** [comment]
On 3DS you can just install the nightly with the updater
