### ISSUE TITLE
TWiLight Menu ++ Freeze at the NDS menu and can't launch games...?

### ISSUE THREAD

**Issue by SenchiRaven** [RocketRobz/TWiLightMenu#494]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _7.4.0_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

TWiLight Menu ++ Should show the NDS menu and launch the game played or access the menus like the settings

### Actual behaviour

I use TWiLight Menu for months without having any trouble, but now, I can't use it anymore, when I launch it and access the NDS-like menu, it freeze. The only thing I can do is going back to the 3DS menu or turn off the console. I tried installing it again, it work... Untill I launch a game, almost all of the games I have do a white screen after loading, except Pokemon Mystery Dungeon Explorer Of Sky, that launch, but after pressing start after the intro, it does a black screen.
I have no idea why that's doing this... Help would be appreciated. ^-^

### Steps to reproduce

1. Launch TWiLight Menu ++ while having launched a game before
2. Profit

**Comment by arraystock** [comment]
Have you tried 7.4.1? I would try that, and if there’s no change I would try the latest nightly. But this sounds like a nds-bootstrap issue to me.

Also, delete your ini file that contains your settings, if neither of the things above work. Maybe you have a setting that’s causing this.

**Comment by SenchiRaven** [comment]
None of them fix my problem, even deleting the settings files.... I'm sorry :/

**Comment by arraystock** [comment]
Don’t be sorry, you’ve done nothing wrong! Do you have the latest nds-bootstrap release? Have you tried its latest nightly?

**Comment by SenchiRaven** [comment]
I do tried using its latest nightly. But it still dosn't work. :/

**Comment by NightYoshi370** [comment]
If you're using the latest nightly of nds-bootstrap, you should use the latest nightly of Twilight.

**Comment by DSIXL** [comment]
So I threw my DSI xl in the water, And it doesnt work. How can i fix this?

**Comment by NightYoshi370** [comment]
It's so hard to take you seriously, but unfortunately, I still need to abide by my policy of professional replies.

That would be a hardware error, and TWiLight Menu++ cannot fix that. Please place it in uncooked rice and see if that fixes it.
If not, Google your issue and attempt the instructions there
