### ISSUE TITLE
Getting the message "error press power to turn off" after booting TwilightMenu++

### ISSUE THREAD

**Issue by MarkGuima** [RocketRobz/TWiLightMenu#498]
-->
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

After all steps done, the menu should appears letting choose the roms

### Actual behaviour

After all steps done and booting displays the DS logo, and when i press to continue, the screen turns black and show the following message: "A error appened, press the power button to turn off the console"

### Steps to reproduce

1. Install via update
2. update again, just for safe
3. Install the Launcher, try to use and get the same error

**Comment by RocketRobz** [comment]
Sounds like you're not on the latest version of the Updater.
It replaces the Launcher.

**Comment by MarkGuima** [comment]
I've updated on the last version in the Updater itself, but when i install the updater doesn't show the option to boot the Twilight itself

**Comment by RocketRobz** [comment]
Because it's not a launcher now.
The app has to be launched from the 3DS HOME Menu now.

**Comment by MarkGuima** [comment]
Right, I've downloaded all again and tried to do it manually.
I can install the game booter, but when i try to install the TWilight Menu.cia the FBi shows me the message: "Failed to install the CIA file, Error Code 0xD8E0800B - Level Permanent 27"

**Comment by RocketRobz** [comment]
Try deleting a DSiWare title from System Memory.

**Comment by MarkGuima** [comment]
Still getting the same error :/

**Comment by RocketRobz** [comment]
How much TWLNAND space is left, in FBI?

**Comment by MarkGuima** [comment]
Sorry, 130,6mb

**Comment by RocketRobz** [comment]
That's strange. It should install then.
Can you show a screenshot of the error?

**Comment by MarkGuima** [comment]
![IMG_20190314_000830 1](https://user-images.githubusercontent.com/48526749/54328698-a3d93e80-45ed-11e9-820d-c44deb8b8913.jpg)

**Comment by MarkGuima** [comment]
I get the same error if i install on DevMenu

**Comment by RocketRobz** [comment]
The updater should've installed that CIA.

**Comment by MarkGuima** [comment]
Oh, begin everything from zero. 
I'm installed the Updater (version 3.0.0)
Downloading the TWilight Menu++ and the NDS thing.
After that i've to install the Launcher, right?

**Comment by Volti-p** [comment]
No you launch the DSiWare.

**Comment by MarkGuima** [comment]
Oh, ok.
It may look a little bit stupid, but where i found the DSiWare option? Is in option menu? If so, i've tryied to, but i get a black screen with error.

**Comment by RocketRobz** [comment]
It's the TWLMenu++ animated icon.
If it black screens with an error message, then if you're using EmuNAND, install the CIAs to SysNAND.

**Comment by MarkGuima** [comment]
I've installed on SysNand, updated. Now when i open the TWLMenu++ DSiWare, gets me a black screen again.

**Comment by RocketRobz** [comment]
Did you install both the regular and Game booter CIAs?

**Comment by NightYoshi370** [comment]
Wait, are you using an EmuNAND?
You should try updating your setup to Boot9Strap and the latest LumaCFW.

**Comment by MarkGuima** [comment]
Yes, i've stalled both CIAs
Yes NightYoshi, I use LumaCFW

**Comment by WrenchMonki** [comment]
Hi, I'm having a similar issue as the original thread title. After installing manually got me the error message, I tried reinstalling through the updater, but whenever I launch the DSiWare the screen with the error notification still pops up. I'm on latest Luma and using b9s.

![IMG_20190314_152231](https://user-images.githubusercontent.com/48548089/54341745-2fde7b00-466d-11e9-9490-75d2ac48951c.jpg)

**Comment by NightYoshi370** [comment]
Actually, you will need to reinstall a clean TWL_FIRM cia files.
There is a tutorial on how to do that in the 3DS Hacking guide, but I forgot the link.

If that isn't the issue, i'll reopen this thread but otherwise I'm gonna close this
