### ISSUE TITLE
when will this be ready for release

### ISSUE THREAD

**Issue by snes666** [RocketRobz/TWiLightMenu#501]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by snes666** [comment]
when will this be ready for release I've been waiting forever

**Comment by snes666** [comment]
@RocketRobz

**Comment by Volti-p** [comment]
Huh? What should be Ready for release?

**Comment by snes666** [comment]
twilight menu ++

**Comment by Volti-p** [comment]
Ehh.. TWiLightMenu has already 99 Releases..

**Comment by snes666** [comment]
when will the new realese be ready

**Comment by Volti-p** [comment]
It will be Ready when it's Ready. You can get the Nightly Version/latest Commit with the TWiLightMenu Updater.

**Comment by snes666** [comment]
thx

**Comment by snes666** [comment]
can you show me a link for this twilight menu updater

**Comment by Volti-p** [comment]
You can get the CIA of the Updater here : https://github.com/RocketRobz/TWiLightMenu-Updater/Releases

**Comment by snes666** [comment]
the only problem is I have a dsixl

**Comment by Volti-p** [comment]
Then download this : https://github.com/TWLBot/Builds/releases/tag/v20190315-042116

**Comment by snes666** [comment]
how do I get prerelease of nds bootstrap

**Comment by snes666** [comment]
is there a special  way to update this or just the normal way

**Comment by Volti-p** [comment]
You extract the `.7z` File and you drag and drop the Contents to the SD Card. (Like the normal way.)

**Comment by DragonautMk** [comment]
New3ds, luma, Release
