### ISSUE TITLE
Super Mario 64 DS Freezes After Nintendo Screen

### ISSUE THREAD

**Issue by YESPLZOK** [RocketRobz/TWiLightMenu#502]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[newest one i think]_
- [x]  Nightly _[newest one again]_

### Expected behaviour
SM64DS should boot up as usual.

### Actual behaviour
SM64DS freezes on a black screen shortly after the Nintendo logo fades away.

### Steps to reproduce

1. Boot up the game with the setup shown above
2. The game will crash
3. (Nothing happens)

**Comment by RocketRobz** [comment]
That issue occurred in nds-bootstrap, not TWLMenu++.
Also, please switch to HiyaCFW.
