### ISSUE TITLE
ERROR POKEMON GAMES NDSI XL

### ISSUE THREAD

**Issue by edrianway** [RocketRobz/TWiLightMenu#504]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [  ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [  ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen
*I SPEAK SPANISH*
Hola a todos tengo un problema acerca de el TWL++,  hace poco instale en 2 consolas una dsi normal y una dsi Xl. Ambas con el mismo correcto proceso de instalacion, pasa que al emular los juegos (pokemon heartgold y soulsilver) en la XL cada que cargo una partida guardada me sale un pantallazo azul que hubo error de conexion y q pulse el boton A. Mientras en la dsi normal no tengo ese problema, solo ocurre con esos juegos de pokemon. NECESITO AYUDA

### Actual behaviour

Tell us what happens instead
La consola no me deja cargar mis partidas intente colocando la SD de mi dsi normal y aun asi me salta el pantallazo al gargar las partidas, intente parchar los juegos con el AP PATCH y aun asi no funcionan. Cabe recalcar que en la dsi normal tengo los roms parchados

### Steps to reproduce

1.
2.
3.

**Comment by arraystock** [comment]
Hola! I will try to help you in Spanish, but my native language is English.

Dijiste las salvaciones del trabajo normal de DSi en la XL? Si sí, entonces tus partidas guardadas en la XL son probablemente malas (corrupt). ¿Qué sucede si borras (o cambias el nombre) del guardado y luego ejecutas el juego?

Perdon por mi mal espanol ;)
(También, disculpa si entendí mal.)

**Comment by edrianway** [comment]
I will start using the google translator to express myself better in English.
Well, every time I change the name to the savs of the roms, the same thing happens, the blue screen appears, marking the error.
As I said, it only happens with pokemon games, it's more if I erase the sav and start a new game, the next time I load that same game I get the same error.
Excuse this English, it's the translator's

**Comment by RocketRobz** [comment]
Please install Unlaunch and HiyaCFW.
