### ISSUE TITLE
Somehow all my roms got deleted.

### ISSUE THREAD

**Issue by Rodokami** [RocketRobz/TWiLightMenu#510]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X ]  Release _[7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour
Cheats working and game starting,

Tell us what should happen

### Actual behaviour
Cheats works sometimes, and sometimes they dont and crash the game (white screen)
Tell us what happens instead
Sometimes cheats wouldn't work and that's fine, I would restart the launcher and try again. This last time though something really bad happened. I activated the cheats and launched Pokemon Platinum and Twilight crashed. I restarted and for some reason all my roms were deleted from my sd. I double checked the folder with fbi and on the pc. The roms are gone. In it's place though are the saves folder which is empty (the saves got deleted too) and the fonts and themes folder. These last 2 folders weren't here before though. 
### Steps to reproduce

1. Twilight Release version and bootstrap nightly
2. Activate more than 3 cheats
3. launch game, (in this case pokemon platinum)

**Comment by RocketRobz** [comment]
Sounds like an issue with your SD card.
I never had this issue.
