### ISSUE TITLE
will this work with twilight menu ++

### ISSUE THREAD

**Issue by snes666** [RocketRobz/TWiLightMenu#511]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by snes666** [comment]
I'm trying to run NDS-GBA @RocketRobz

**Comment by snes666** [comment]
@Volti-p

**Comment by dubbz82** [comment]
Issue isn't defined in the template nor is enough information given in the description about the systems setup.  This should be closed out.

**Comment by Volti-p** [comment]
For Question like that, come to the RocketChat Server or come to the discord Server.
