### ISSUE TITLE
 no title.tmd or main_srldr when reinstalling twilight menu ++

### ISSUE THREAD

**Issue by snes666** [RocketRobz/TWiLightMenu#512]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by snes666** [comment]
can anyone help quickly i really need help

**Comment by snes666** [comment]
@Volti-p

**Comment by snes666** [comment]
@NightYoshi370

**Comment by NightYoshi370** [comment]
What?

**Comment by dubbz82** [comment]
Please stop pinging people directly, and please fill out the issue template more completely.  If it's something you feel can't be easily explained in a github issue, you're better off coming to discord or rocket.chat and discussing it there.

**Comment by RocketRobz** [comment]
^ this

Please stop using the issue tracker for assistance purposes.
Visit this page to see the links for the Discord and Rocket.Chat servers: https://gbatemp.net/threads/ds-i-noob-paradise-ask-questions-here.528133/
