### ISSUE TITLE
New game not shown if the blocks were rearranged

### ISSUE THREAD

**Issue by naytai** [RocketRobz/TWiLightMenu#518]
TWiLightMenu won't show recent added games to the SD card, if the blocks positions were rearranged previously.
In order to make them appear, I have to delete the gameorder.ini file, loosing my customized order.

I am using TWiLightMenu 7.4.1 configured to hide directories. Rom files are in SD root.

**Comment by NightYoshi370** [comment]
Incorrect: They appear at the end of the list. I tested this myself.

**Comment by naytai** [comment]
@NightYoshi370 That's right
My bad
Sorry for this
