### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by JoseTheNiceGuy** [RocketRobz/TWiLightMenu#522]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[]_
- [x]  Unlaunch+HiyaCFW _[Latest HiyaCFW, Unlaunch 0.8]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When I turn on my DSi XL, after the HiyaCFW splash screen, it will boot to the program

### Actual behaviour

When I turn it on using a 4GB with Autoboot enabled, it gives me a white screen.

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Try @Epicpkmn11's HBChecker, and see if there's issues.

**Comment by Epicpkmn11** [comment]
(This btw: https://epicpkmn11.github.io/HBChecker/)

**Comment by JoseTheNiceGuy** [comment]
It gives me an error saying api-ms-win-crt-runtime-l1-1-0.dll is missing

**Comment by Epicpkmn11** [comment]
Huh, I've never heard of it doing that before... Maybe try getting [Python](https://www.python.org) and running the `HBChecker.py` file

**Comment by JoseTheNiceGuy** [comment]
I have python installed

**Comment by Epicpkmn11** [comment]
Does running `HBChecker.py` work?

**Comment by JoseTheNiceGuy** [comment]
how do I do it, I use Python 2.7, and it has invaild syntax

**Comment by Epicpkmn11** [comment]
I thought it worked in Python 2... Are you able to run it in Python 3?

**Comment by JoseTheNiceGuy** [comment]
If I open python 3, it says api-ms-win-crt-runtime-l1-1-0.dll is missing

**Comment by Epicpkmn11** [comment]
Oh, and it does that on the `.exe` version too, right?

**Comment by JoseTheNiceGuy** [comment]
yes

**Comment by Epicpkmn11** [comment]
(From [here](https://answers.microsoft.com/en-us/windows/forum/windows8_1-pictures-musicapp/api-ms-win-crt-runtime-l1-1-0dll-is-missing/b593b94e-6691-423b-a586-0b7f10131e35)) it seems you might need to install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-in/download/details.aspx?id=48145)

**Comment by JoseTheNiceGuy** [comment]
there we go, it works on python 2

**Comment by JoseTheNiceGuy** [comment]
It seems like it works fine now, When I used HiyaCFW helper, It gave me mount failed

**Comment by NightYoshi370** [comment]
> It seems like it works fine now

Do you mean TWiLightMenu++ works fine now or HiyaCFW helper works fine now?

**Comment by NightYoshi370** [comment]
I'm assuming you mean TWiLightMenu++ because of the following statement, so I'll close this issue
