### ISSUE TITLE
 Some games show card extracted error

### ISSUE THREAD

**Issue by vivanlaslolis89** [RocketRobz/TWiLightMenu#523]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ x]  Unlaunch+HiyaCFW _[unlaunch 0.8/I dont know hiya version]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[7.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

I click on some games for example Dragon ball supersonic warriors and it should start correctly but afew seconds after starting it shows card extracted error.

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
That issue is fixed in the next nds-bootstrap version.

**Comment by vivanlaslolis89** [comment]
I,ve updated all but it still doing what after does
now im in bootstrap 0.17.1 and twilight 7.4.1
sorry for being a little bit annoying T-T

**Comment by Volti-p** [comment]
He said in the `Next` Version. Not the current Version.

**Comment by vivanlaslolis89** [comment]
ah ok i,ll try then
