### ISSUE TITLE
Where is a TwilightMenu++ Shop?

### ISSUE THREAD

**Issue by crensyhanilas** [RocketRobz/TWiLightMenu#525]
TwilightMenu++ Shop is Missing. Can You Reply Please? You should Invite me on discord server.

**Comment by Ty-Dye** [comment]
Discord invite


https://discord.gg/XRXjzY5

**Comment by Stack3r** [comment]
What exactly is TwilightMenu++ shop?

**Comment by NightYoshi370** [comment]
If you'd like to have a place to talk about TWiLightMenu, please read the Readme. It links to the Rocket.Chat server

**Comment by crensyhanilas** [comment]
I created DanysMenu++
https://github.com/danys2019/DanysMenu

if you have a issue, join https://discord.gg/MnBzV4T

**Comment by Stack3r** [comment]
Previous comment deleted
*No self promoting, this is an issue reporting section*
