### ISSUE TITLE
Black Screen in FF 4 Heroes of Light

### ISSUE THREAD

**Issue by TheFlintASteel** [RocketRobz/TWiLightMenu#532]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[Release 7.4.1]_ 
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

When Twilight Menu++ load the game instantly the screen puts in black don't do anything else

**Comment by MasterGamingYT** [comment]
´´If an issue happens in a DS game itself, please post to nds-bootstrap issue tracker instead´´

**Comment by FlameKat53** [comment]
> https://github.com/RocketRobz/TWiLightMenu/issues/532#issuecomment-480991451

Seconding this as it is true and says it in the issue template
