### ISSUE TITLE
White Screen Pokemon V gen

### ISSUE THREAD

**Issue by Sherlockowiec** [RocketRobz/TWiLightMenu#533]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release (7.4.1)
- [ ]  Nightly

I'm trying to play Pokemon White and Pokemon Black 2, I downloaded both AP patched, I select the rom, save file created successfully, loading screen and after that screen remains white.
I tried different roms, patched, clean, from different sources but nothing. 
I played New super mario bros, pokemon Heartgold, Pokemon Platinum and it worked without issue.

**Comment by FlameKat53** [comment]
1.) set the game to DS Mode with VRAM Boost off

2.) this is *not* an issue with TWiLight menu++
