### ISSUE TITLE
immediate crash when starting it up

### ISSUE THREAD

**Issue by warrenher** [RocketRobz/TWiLightMenu#542]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[v7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

TWiLight Menu++ is supposed to start up

### Actual behaviour

When starting TWiLight Menu++ up, it immediately crashes (this typical "an error has occured..."-crash). I upgraded from DSiMenu++, what's weird is that DSiMenu++ worked flawlessly. I tried deleting the _nds folder and reinstalling it multiple times.

### Steps to reproduce

can't really reproduce it, maybe upgrading from DSiMenu++ to TWiLight Menu++? All I did was follow the wiki; I tried both the manual and via updater method of installing it.

**Comment by RocketRobz** [comment]
If you're using EmuNAND, install the CIAs to SysNAND as well.

**Comment by warrenher** [comment]
I used to have EmuNAND but I don't have it anymore. I upgraded to boot9strap using 3ds.hacks.guide. The DSiMenu++ version I am upgrading from is (according to FBI): 1040 (1.1.0)

**Comment by RocketRobz** [comment]
Follow this then: https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by warrenher** [comment]
It's working now, thank you!

**Comment by RocketRobz** [comment]
No problem!
