### ISSUE TITLE
More languages and new setting screen.

### ISSUE THREAD

**Issue by anuserlol** [RocketRobz/TWiLightMenu#61]
Probably the developer is adding more languages, but I still wanted to post this.
Good work on the new menu! ;D
Edit: I also think that the blue and red color don't match very well in the logo fom the settings screen, so I thought that a screen like the one from the original DSi settings menu would look better, but it is not a problem, just some improvements in the aesthetics (sorry for my english).
-Sorry if I wrote too many suggestions.

**Comment by Robz8** [comment]
We already have a new logo, and it will be in the next version.

**Comment by anuserlol** [comment]
Thanksgiving!

**Comment by dubbz82** [comment]
Given that numerous languages have been added, and there's a new logo (probably even two) since this request was opened, can this be closed out now?
