### ISSUE TITLE
[Aesthetic suggestion] Config-Card-GBArunner2 menu

### ISSUE THREAD

**Issue by RS55** [RocketRobz/TWiLightMenu#68]
I wanted to suggest that because they are practically shortcuts (or so I think) make them an option in menu like the current Select buttom with the SDK version in the games, something like the initial menu of the R4 original but stylized. Obviously if that is possible.

**Comment by Epicpkmn11** [comment]
Since TWiLight no longer has this menu, this should probably be closed
