### ISSUE TITLE
Allow for Custom Themes without recompiling

### ISSUE THREAD

**Issue by jetlego** [RocketRobz/TWiLightMenu#81]
Looking at the source code, the placement of the files in _nds, and the compiling directions, it appears that in order for a new theme to be created, the files in one of the pre-existing themes would have to be edited, and then subsequently compiled into a binary format. However, in order to do this, one must have a complete working devkitPro environment in which to compile the theme. Additionally, editing either of the current themes is a rather tedious process. 

Would it be possible to add support for theming similar to what the 3DS currently has with Anemone, though without the on-device UI? Or is it unfeasible due to limitations of Easy GL2D and the way themes are structured and launched?

I apologize if this issue is out of scope, and can close it if so.

**Comment by Valkristh** [comment]
+1 to this, i miss seeing an image at the top screen like the system menu

**Comment by RonnChyran** [comment]
Acekard theme in 6.1.0 supports custom sub themes using Acekard/Wood compatible themes. Textures have to be in RGB565 format.

**Comment by DMSalesman** [comment]
To elaborate on a related issue, would it be possible to have a barebones TWiLightMenu++ experience with only the DSi and 3DS themes installed? For instance, I never used any of the AceKard themes and don't even own a flash cart, so the theme files are eating some megabytes in my SD card for nothing.

**Comment by chyyran** [comment]
You can just delete the theme files from the SD card with no issue.

**Comment by DMSalesman** [comment]
Good to know, thanks.

**Comment by FlameKat53** [comment]
Epicpkmn11 is working on this, and it will *likely* (not confirmed) be in v7.4.0

**Comment by NightYoshi370** [comment]
> Epicpkmn11 mentioned that while top screen implementation would be easy, the bottom screen is much more difficult, due to the bottom screen files being compiled from the ARM9 binary.

Didn't the latest commit move them to NitroFS? @Epicpkmn11

**Comment by RocketRobz** [comment]
Yeah, the bottom screen BG images are moved to NitroFS.

**Comment by NightYoshi370** [comment]
So I'm assuming that it's now easier to move these to load from the SD card. Is that correct?

**Comment by RocketRobz** [comment]
Yes.

**Comment by chyyran** [comment]
#439 implements customizable themes for the DSi and 3DS themes, but some textures still require devkitPro installed to customize (to "compile "the theme). Fortunately you won't need to recompile TWiLightMenu++, just the theme itself.

**Comment by NightYoshi370** [comment]
So, uh, I'm not sure if this should be closed or not.
On one end, you don't need to recompile TWLMenu++, you need to recompile the theme.
On the other, the fact that you still need to recompile might not be what the OP meant.

So, uh, I'll leave this issue up to you guys.

**Comment by chyyran** [comment]
Getting the theme to compile and work is much less work than getting TWLMenu++ to compile and work. All you need is grit and make, not even the entire devkitPro environment. The Makefiles are already provided with a handy guide, so that step is as streamlined as possible; the theme maker doesn't even have to worry about whether they're using XRGB1555 for anything that grit compiles.

I highly doubt it will ever be possible to get rid of the dependency on paletted textures in the DSi/3DS theme (and thus requiring grit). There's just not enough memory to fit all the textures needed at once if everything was a bitmap.

**Comment by NightYoshi370** [comment]
> I highly doubt it will ever be possible to get rid of the dependency on paletted textures in the DSi/3DS theme (and thus requiring grit). There's just not enough memory to fit all the textures needed at once if everything was a bitmap.

In that case, I'll close this issue
