### ISSUE TITLE
R4 Upgrade Revolution White Screens

### ISSUE THREAD

**Issue by xyifer12** [RocketRobz/TWiLightMenu#95]
**Your console:** Old 2DS
**CFW:** Luma3DS
**TWiLightMenu++ Version:** 5.00

The system gets stuck with both screens completely white when trying to launch this flashcard:

![image](https://user-images.githubusercontent.com/18664762/53210614-5459b100-35f3-11e9-9f7a-a29845440d9f.png)

**Comment by FlameKat53** [comment]
Does it still do that?

**Comment by NightYoshi370** [comment]
I have tried looking up the firmware online. Unfortunately, I can't find it, so I can't exactly see if I can add launching games to this card, which means I'll need to close the issue.

Once I have the firmware files though, I can then determine whether I can add support for launching games or not.
